### ISSUE TITLE
PANIC  in vim 7.3  windows 7 sp1

### ISSUE THREAD

**Issue by Fanr-F** [nsf/gocode#107]
package main
    import(
        "fmt"
    )
func main(){
    print("hello")
    arr =  []string{"1","2","3"}
    var myerror =  os.NewError("1")
    myerror.
}

when i type c-x c-o 
gocode -s ruturn:
2012/11/14 10:40:34 rpc: rpc: server cannot decode request: WSARecv tcp 12
7.0.0.1:37373: The specified network name is no longer available.

netstat -abn show:

 TCP    127.0.0.1:37373        0.0.0.0:0              LISTENING
[gocode.exe]

go version: go1.0.3
vim version: VIM - Vi IMproved 7.3

**Comment by wheelcomplex** [comment]
Some times, the old version gocode -s(server side) still running in background, and can not work with new version client side, "killall gocode" may fix this. Hope this helps.
