### ISSUE TITLE
The only autocompletion I get is PANIC

### ISSUE THREAD

**Issue by alexaandru** [nsf/gocode#164]
Hello,

Just installed gocode a few minutes earlier and all attempts to get it to work in vim failed. Ultimately, I started a server manually (gocode -s) and then using the gocode client in command line, I tried: "gocode autocomplete math.F" and that resulted in a:

```
Found 1 candidates:
  PANIC PANIC PANIC
```

Verifying the server window that showed:

```
panic: runtime error: index out of range
1(runtime.panic): /usr/local/go/src/pkg/runtime/panic.c:248
2(runtime.panicstring): /usr/local/go/src/pkg/runtime/panic.c:478
3(runtime.panicindex): /usr/local/go/src/pkg/runtime/panic.c:433
4(main.(*tok_collection).find_decl_beg): /home/alex/.go/src/github.com/nsf/gocode/ripper.go:39
5(main.(*tok_collection).find_outermost_scope): /home/alex/.go/src/github.com/nsf/gocode/ripper.go:102
6(main.(*tok_collection).rip_off_decl): /home/alex/.go/src/github.com/nsf/gocode/ripper.go:116
7(main.rip_off_decl): /home/alex/.go/src/github.com/nsf/gocode/ripper.go:133
8(main.(*auto_complete_file).process_data): /home/alex/.go/src/github.com/nsf/gocode/autocompletefile.go:55
9(main.(*auto_complete_context).apropos): /home/alex/.go/src/github.com/nsf/gocode/autocompletecontext.go:241
10(main.server_auto_complete): /home/alex/.go/src/github.com/nsf/gocode/server.go:128
11(main.(*RPC).RPC_auto_complete): /home/alex/.go/src/github.com/nsf/gocode/rpc.go:26
12(runtime.call64): /usr/local/go/src/pkg/runtime/asm_amd64.s:340
13(reflect.Value.call): /usr/local/go/src/pkg/reflect/value.go:474
14(reflect.Value.Call): /usr/local/go/src/pkg/reflect/value.go:345
15(net/rpc.(*service).call): /usr/local/go/src/pkg/net/rpc/server.go:381
16(runtime.goexit): /usr/local/go/src/pkg/runtime/proc.c:1389
```

I am using Go version:
go version devel +f4d1cb8d9a91 Thu Sep 19 22:34:33 2013 +1000 linux/amd64

Please let me know if there's any other info I can provide.

Thank you,
really looking forward to using this in Vim :)

**Comment by kjda** [comment]
same problem here. Go1.4 installed using gvm


```
panic: unexpected token: "?"
1(runtime.panic): /usr/lib/go/src/pkg/runtime/panic.c:248
2(main.(*gc_parser).error): /build/buildd/gocode-0~git20130712/package.go:260
3(main.(*gc_parser).errorf): /build/buildd/gocode-0~git20130712/package.go:264
4(main.(*gc_parser).parse_type): /build/buildd/gocode-0~git20130712/package.go:638
5(main.(*gc_parser).parse_field): /build/buildd/gocode-0~git20130712/package.go:382
6(main.func·016): /build/buildd/gocode-0~git20130712/package.go:528
7(main.(*gc_parser).parse_struct_type): /build/buildd/gocode-0~git20130712/package.go:538
8(main.(*gc_parser).parse_type): /build/buildd/gocode-0~git20130712/package.go:608
9(main.(*gc_parser).parse_type_decl): /build/buildd/gocode-0~git20130712/package.go:718
10(main.(*gc_parser).parse_decl): /build/buildd/gocode-0~git20130712/package.go:827
11(main.(*gc_parser).parse_export): /build/buildd/gocode-0~git20130712/package.go:854
12(main.(*package_file_cache).process_package_data): /build/buildd/gocode-0~git20130712/package.go:133
13(main.(*package_file_cache).update_cache): /build/buildd/gocode-0~git20130712/package.go:91
14(main.func·002): /build/buildd/gocode-0~git20130712/autocompletecontext.go:325
15(runtime.goexit): /usr/lib/go/src/pkg/runtime/proc.c:1394

panic: One of the package cache updaters panicked
1(runtime.panic): /usr/lib/go/src/pkg/runtime/panic.c:248
2(main.update_packages): /build/buildd/gocode-0~git20130712/autocompletecontext.go:333
3(main.(*auto_complete_context).update_caches): /build/buildd/gocode-0~git20130712/autocompletecontext.go:165
4(main.(*auto_complete_context).apropos): /build/buildd/gocode-0~git20130712/autocompletecontext.go:246
5(main.server_auto_complete): /build/buildd/gocode-0~git20130712/server.go:122
6(main.(*RPC).RPC_auto_complete): /build/buildd/gocode-0~git20130712/rpc.go:25
7(runtime.call64): /usr/lib/go/src/pkg/runtime/asm_amd64.s:340
8(reflect.Value.call): /usr/lib/go/src/pkg/reflect/value.go:474
9(reflect.Value.Call): /usr/lib/go/src/pkg/reflect/value.go:345
10(net/rpc.(*service).call): /usr/lib/go/src/pkg/net/rpc/server.go:381
11(runtime.goexit): /usr/lib/go/src/pkg/runtime/proc.c:1394
```

**Comment by nsf** [comment]
@kjda Nah, yours is not the same as this one. Yours is more like this: https://github.com/nsf/gocode/issues/225

**Comment by nsf** [comment]
@kjda See this issue in general: that's the original one: https://github.com/nsf/gocode/issues/163

**Comment by kjda** [comment]
@nsf it doesn't work regardless of the imported package.. fmt., log., myownpkg.  , etc.. I always get PANIC.. however, it does autocomplete variables or functions defined in the same file. ```go get -u github.com/nsf/gocode````does not help

**Comment by nsf** [comment]
It's possible that there are multiple gocode binaries for whatever reason. What `which -a gocode` says?

**Comment by kjda** [comment]
´´´
/usr/bin/gocode
/var/www/go/bin/gocode
´´´
removing either of them did not help( mv /usr/bin/gocode /usr/bin/gocode-backup).. not sure if this is the right way to do it

I also noticed that just by opening a .go file the status bar shows "vim-go: PANIC PANIC PANIC"

**Comment by nsf** [comment]
Oh, I forgot to tell you to actually restart gocode. Because if you updated it, it won't work as is, since there is an actual process running already. Do: `gocode close`. It will kill the server and will start a new one automatically. Or just reboot if you wish.

**Comment by kjda** [comment]
Super! Thanks man! +++

**Comment by akarki15** [comment]
had the same problem. this fixed it!! thanks a lot!
🙌 🙌 🙌 🙌 🙌 🙌 🙌 🙌

**Comment by integrii** [comment]
I was getting this in atom with go-autocomplete, but simply running `gocode close` fixed the issue!

**Comment by sksea** [comment]
`gocode close` didn't work for me. Had to remove `gocode` listed at `which -a gocode` and reinstall it via `go get -u`.

**Comment by gopherliu** [comment]
@samuell ,  in vim-go , go1.7 , have the same problem

**Comment by jphenow** [comment]
@gopherliu did you try `go close` since the update? That ended up working for me after updating gocode and vim-go

**Comment by akarki15** [comment]
http://giphy.com/gifs/the-it-crowd-chris-odowd-F7yLXA5fJ5sLC

**Comment by nsf** [comment]
Yeah, I kind of regret not embedding the version info into gocode binaries and checking those on each client/server communication. Could solve some of your user experience issues.

**Comment by 4ydx** [comment]
Had the same issue.  Just killing the process wasn't good enough.  Had to delete the socket file as well.  Just do what samuell suggested above.

**Comment by mewben** [comment]
Thanks. Updating gocode works for me.

**Comment by cyberswat** [comment]
Here's the one liner to update gocode

```gocode close && go get -u github.com/nsf/gocode```

**Comment by AlexeiSuleac** [comment]
gocode close helped me as well here...

**Comment by frank0718** [comment]
atom got  this problem ;  gocode close && go get -u github.com/nsf/gocode ; reopen atom;  works like a charm

**Comment by hongguangli** [comment]
sudo apt-get remove gocode

**Comment by kovetskiy** [comment]
@hongguangli a troll detected.

**Comment by rayxyz** [comment]
I just clear the $GOPATH/pkg/linux_amd64 folder, and fixed it.
```
ray@ray-pc:~/go_workspace/pkg/linux_amd64$ sudo rm -rf *
```
