### ISSUE TITLE
gocode fails to pick up any packages

### ISSUE THREAD

**Issue by mattknox** [nsf/gocode#256]
Regardless of my setting of gocode set lib-path , I can never get gocode to pick up any packages.  

matts-MacBook-Pro:src mattknox$ echo $GOPATH
/Users/mattknox
matts-MacBook-Pro:src mattknox$ echo $GOROOT
/usr/local/opt/go/libexec/

I've tried gocode set libpath X for the following values of X:
 gocode set lib-path "/Users/mattknox/pkg"
 gocode set lib-path ""
 gocode set lib-path "/Users/mattknox/pkg/darwin_amd64/

It seems like this should have worked-what am I doing wrong?

2014/11/10 17:01:09 Import path "fmt" was not resolved
2014/11/10 17:01:09 Gocode's build context is:
2014/11/10 17:01:09  GOROOT: /usr/local/opt/go
2014/11/10 17:01:09  GOPATH: /Users/mattknox/src
2014/11/10 17:01:09  GOOS: darwin
2014/11/10 17:01:09  GOARCH: amd64
2014/11/10 17:01:09  lib-path: "/Users/mattknox/pkg/darwin_amd64/"

2014/11/10 16:51:23 Import path "fmt" was not resolved
2014/11/10 16:51:23 Gocode's build context is:
2014/11/10 16:51:23  GOROOT: /usr/local/opt/go
2014/11/10 16:51:23  GOPATH: /Users/mattknox/src
2014/11/10 16:51:23  GOOS: darwin
2014/11/10 16:51:23  GOARCH: amd64
2014/11/10 16:51:23  lib-path: "/Users/mattknox/pkg"

2014/11/10 16:59:55 Import path "fmt" was not resolved
2014/11/10 16:59:55 Gocode's build context is:
2014/11/10 16:59:55  GOROOT: /usr/local/opt/go
2014/11/10 16:59:55  GOPATH: /Users/mattknox/src
2014/11/10 16:59:55  GOOS: darwin
2014/11/10 16:59:55  GOARCH: amd64
2014/11/10 16:59:55  lib-path: ""

**Comment by edofic** [comment]
@nsf is there any particular reason it doesn't look at the source? Or can this be enabled? 
I'm trying to use gocode with a project that doesnt' have `pkg` for some reason.

**Comment by nsf** [comment]
@edofic It's for historical reasons. In the beginning there was no GOPATH and we didn't know anything about where the package comes from, there was only GOROOT and lib packages inside.

It's possible to use sources, but gocode doesn't do so, unless someone implements it. I lack interest.
