### ISSUE TITLE
Feature request: autocomplete for import

### ISSUE THREAD

**Issue by kokizzu** [nsf/gocode#257]
When typing inside import, there should be autocomplete containing all libraries that have been installed.

![image](https://cloud.githubusercontent.com/assets/1061610/5163887/35e1b1f2-7403-11e4-9aee-d02f4cb4df1c.png)

**Comment by nhooyr** [comment]
I'm gonna take a stab at implementing this.

**Comment by nsf** [comment]
Good luck, I would start from here: https://github.com/nsf/gocode/blob/master/cursorcontext.go#L272

You need to figure out somehow that the cursor is on the import clause. Maybe do some sort of reverse parsing. This function above actually does tokenize code, but you should take care about a common case when string literal isn't valid, e.g.:

```go
package main
import (
  "io/
)
```

In this case tokenizer may actually fail. But there are hacks to avoid that, you can try detecting if amount of quotes before the cursor is odd (be careful about possible quotes in comments) and insert a quote after the cursor. All sorts of hacks may work. It's definitely possible to do a solid context detection here, but may take some time.

**Comment by nhooyr** [comment]
@nsf thanks.
