### ISSUE TITLE
How do I set up $GOPATH properly for Emacs?

### ISSUE THREAD

**Issue by arianitu** [nsf/gocode#261]
It always takes me an hour to get gocode to work and usually it's random. It also tends to break at random as well. 

Where does gocode look for $GOPATH?

Here are some of the things I've tried.. in my emacs:

```
(setenv "GOPATH" "/Users/auka/Development/personal/go")
(setq exec-path (append exec-path '("/usr/local/Cellar/go/1.3.3/bin")))
(setq exec-path (append exec-path '("/Users/auka/Development/personal/go/bin")))
(setenv "PATH"
        (concat
     "/usr/local/Cellar/go/1.3.3/bin" ":"
     (getenv "PATH")
     )
    )
```

in my .zshrc:

```
export GOPATH=$HOME/Development/personal/go
```

Is it using the one in .zshrc, or the one in .emacs, or neither? 

I use http://emacsformacosx.com/, so I'm not sure where all the paths are coming from, it's extremely frustrating.

If I run this go env in my zsh terminal I get:

```
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/auka/Development/personal/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.3.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.3.3/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

Is gocode suppose to run from the zsh terminal, or is the emacs plugin suppose to launch it for you? Are the paths different if you launch it your self?

Is there an easy way to debug what's happening under the covers instead of me hitting tab and nothing happening?

**Comment by sunlightlj** [comment]
@nsf @arianitu 
This issue could be solved by following step
#echo "export GOPATH="YOUR-GO-PATH" >> ~/.profile

More info:
http://stackoverflow.com/questions/18773051/how-to-make-os-x-to-read-bash-profile-not-profile-file
