### ISSUE TITLE
How can I avoid this window appeared?

### ISSUE THREAD

**Issue by jas0ns** [nsf/gocode#267]
I don't like the window in the red box cause I don't need the content in that window. How can i avoid this window appeared? Thanks.
![qq 20150109100209](https://cloud.githubusercontent.com/assets/8058809/5674521/cc6598d0-97e6-11e4-8df2-a6a7d7050211.jpg)

**Comment by nsf** [comment]
Is it vim? In vim you can disable it with: `set completeopt-=preview`

**Comment by jas0ns** [comment]
Resolved. Thank u very much!
