### ISSUE TITLE
Windows Compilation Trouble - decl.go:94: undefined: scope

### ISSUE THREAD

**Issue by Tybogy** [nsf/gocode#269]
Hi,

I am not able to compile gocode on a fresh Windows 7 x64 install using go version 1.4.  The following error appears when compiling:

```
go get -u -ldflags -H=windowsgui github.com/nsf/gocode
# github.com/nsf/gocode
.\decl.go:94: undefined: scope
```

...I've cleared out the source folder and confirmed that the latest version of the code is installed.  Go is configured correctly on the machine and I am able to compile other projects.

Please let me know if you need any additional information.

**Comment by nsf** [comment]
Weird issue, will try to reproduce it on my windows machine. The scope type is defined in scope.go, have no idea why it suddently things it's not there.

**Comment by shurcooL** [comment]
There is no mention of `scope` on line 94 of `decl.go`, it's a blank line. `scope *scope` is on line 97. Perhaps it's a newline issue? Would `gofmt -w ./` help?

**Comment by Tybogy** [comment]
"Scope.go" was completely missing from my local pull.  I manually copied the raw "scope.go" source from the main page and the project built without issue.

Perhaps this was a local issue with git?  Again, I emptied the local source folder and ran go get per the project's instructions ( go get -u -ldflags -H=windowsgui github.com/nsf/gocode ).  Not sure why the file went missing.

**Comment by nsf** [comment]
Weird indeed. But have no clue why it happens.

**Comment by Tybogy** [comment]
I don't believe the issue was with windows newlines, shur.  If you're running Windows, perhaps you clear out your local copy and pull down gocode again with go get to see whether the "scope.go" is being pulled down?

**Comment by nsf** [comment]
Tried it on my windows machine. Did: `go get -u -ldflags -H=windowsgui github.com/nsf/gocode`. The `scope.go` is there, builds fine. Try reinstalling git maybe or something, I don't know.

**Comment by shurcooL** [comment]
It still doesn't explain the 94 vs 97 line mismatch. On my machine, if I `rm scope.go` and do `go build`, I get:

```
./decl.go:97: undefined: scope
```

Where 97 is the correct line. 94 is not.

**Comment by Tybogy** [comment]
shur,

In my decl.go, line 97 is "func ast_decl_type(d ast.Decl) ast.Expr {", whereas line 94 is "	scope *scope".  Not sure why the source would be different.  I have run "gofmt -w ./" and the line numbers did not change.  Again, this is a fresh install of Windows 7, a new go 1.4 installation, and new copy of git (1.9.5.msysgit.0).

I'm going to close this issue as it seems to be a problem confined to my PC.  Thanks for the assistance.

**Comment by shurcooL** [comment]
Yep, that's strange. You can see the source of `decl.go` on github: https://github.com/nsf/gocode/blob/3109790fda3785bbad336e3dd85aaaa4604dbe8b/decl.go#L97.

**Comment by nsf** [comment]
Well, it actually was on line 94 at some point. E.g.

https://github.com/nsf/gocode/blob/8ce369591f51f0b00a5248f9a1dfd50e691b75f6/decl.go
