### ISSUE TITLE
Emacs - go-autocomplete - "dot" manual complete

### ISSUE THREAD

**Issue by mikefaille** [nsf/gocode#271]
Hi folks. 
I try to use go-autocomplete with emacs and I can't complete code after dots.

For example, when I press <tab> key using go-complete for auto-complete after this 
```os. ```
nothing appends.
But, when I use ```M ac-complete-go``` it work.

So, I  correctly load go-autocomplete.

Note that, when i'm in go-mode for edit go files, I have following entry in following lists :
In ```ac-mode``` list, I retrieve :```go-mode```
In ```ac-sources``` list, I retrieve ```ac-source-go```.

English isn't my first language. So, if my explanation isn't sufficient, I can present a 20 sec video to expose my current problem. 

Note : I reference the same bug here  https://github.com/auto-complete/auto-complete/issues/387 cause this bug could be resolve at auto-complete core module.

**Comment by mikefaille** [comment]
In https://github.com/nsf/gocode/blob/b6fffd0527b4ab22df0170d7243317ab2773622e/emacs/go-autocomplete.el
I try adding this at line 197 :
```(add-hook 'go-mode-hook '(lambda ()
                           (add-to-list 'ac-omni-completion-sources ;; My addition
                                        (cons "\\." '(ac-source-semantic))) ;; My addition
                           (add-to-list 'ac-sources 'ac-source-go)))```
but, it doesn't work...

**Comment by nsf** [comment]
My first suggestion is to try company-mode. That's the one I use and I find it easier to work with. As for auto-complete-mode, it works for me this way:

I put the `go-autocomplete.el` to `~/.emacs.d/manual` dir.

Then I add the following lines into my `~/.emacs.d/init.el`:

```
(add-to-list 'load-path "~/.emacs.d/manual")
(require 'go-autocomplete)
(require 'auto-complete-config)

(add-hook 'go-mode-hook (lambda () (yas-minor-mode) (auto-complete-mode)))
```

Auto-complete-mode itself is installed via ELPA (http://emacswiki.org/emacs/ELPA).

And it works after typing "dot".

Have no idea what it might be in your case.

**Comment by nsf** [comment]
When you're editing a Go file does it show the "AC" in status bar?

**Comment by mikefaille** [comment]
@nsf  Yes, it's true. Company mode work but i really want fuzzy completion for auto-complete menu.

In the auto-complete side (yes, I think it was a good idea to cross reference this bug..)
Someone have the bug I have. https://github.com/auto-complete/auto-complete/issues/387
You can see it in this short demo : http://youtu.be/IfWHItWoymg

> Then I add the following lines into my ~/.emacs.d/init.el: (...)
> Auto-complete-mode itself is installed via ELPA (...)
I'll try it right now from an empty config. (with go mode, ac and, go-autocomplete for sure! )

**Comment by nsf** [comment]
Well, the amount of modes you use is quite impressive, so.. I can only guess where things can go wrong.

**Comment by mikefaille** [comment]
@nsf 
I have exactly the same bug.  Voila my clear config for testing it (with my go-code integration...).
https://gist.github.com/mikefaille/abf77eea7b412502d751

**Comment by syohex** [comment]
@mikefaille I fixed this issue and its patch was merged. Please check latest auto-complete.

**Comment by mikefaille** [comment]
Yes, this commit have fixed my problem ! I have update directly from melpa and it works !
https://github.com/auto-complete/auto-complete/commit/4223a2a6fee5e9f3afd1646808043b5c5928757b

**Comment by nsf** [comment]
Great, closing the issue then?

**Comment by mikefaille** [comment]
Yeah, for sure. ! Thank you mister.
