### ISSUE TITLE
PANIC PANIC PANIC

### ISSUE THREAD

**Issue by wwalker** [nsf/gocode#272]
In vim, put your cursor after the word "files", enter insert mode ('a') and add a '.'

boom!

If the block comment is closed first, it is not a problem.

This is only a problem because I spent a while trying to figure out what was throwing the error...
 
```
// Author wwalker

/*
The script files
package main

import (
  "asdf"
)
```

**Comment by jussij** [comment]
FWIW this works as expected inside the Zeus IDE, because it knows that cursor location is inside a comment block and as such it doesn't fire the autocomplete for the '.' character.

It might be possible for the vim plug-in to fix this issue with a similar test.

**Comment by nsf** [comment]
Yes, but gocode shouldn't panic when parsing fails. It should silently return nothing.
