### ISSUE TITLE
go install requires root

### ISSUE THREAD

**Issue by bfrog** [nsf/gocode#273]
when running go install in gocode I now get...

```sh
go version
go version go1.4.2 linux/amd64
go install
go install net/rpc: open /usr/lib/go/pkg/linux_amd64/net/rpc.a: permission denied
```

**Comment by nsf** [comment]
Something is wrong with your Go installation probably. See what it says: `open /usr/lib/go/pkg/linux_amd64/net/rpc.a: permission denied`. It doesn't write there, it reads the package. If it has a problem reading it - something is wrong with your Go installation.

**Comment by jwadsager** [comment]
I have this issue as well and I don't think my Go installation is broken. It's the stock Arch Linux package.

**Comment by dominikh** [comment]
The stock Arch package has been broken (in exactly the same way) countless times... Check if the mtimes for the source files of the stdlib are newer than those of the object files.

**Comment by nsf** [comment]
Yeah, I love arch packages when they make sense. But there are things where they don't. I don't know the status of Go packages in various distros, but building by hand works just fine. Go is not GCC also, it builds in like 1 minute max (or more like 30 seconds). Roughly I do the following: clone repo to ~/go, build via make.bash (all.bash also runs tests), add GOPATH=~/waytogo, add ~/waytogo/bin and ~/go/bin to PATH, done.

**Comment by ronin13** [comment]
Hit the same issue, I think it is related to https://github.com/golang/go/issues/5064 (linked here https://bugs.archlinux.org/task/41561)

I fixed this with  - ```sudo go install net/rpc``` (this actually just bumps the file timestamp)  followed by ```go install github.com/nsf/gocode```.

**Comment by nsf** [comment]
Anyways, it's not a gocode issue at all. Closing it.
