### ISSUE TITLE
Melpa stable for emacs-company

### ISSUE THREAD

**Issue by nlamirault** [nsf/gocode#274]
could you please create a tag to use this package using melpa stable [1].
Thanks

[1] : http://stable.melpa.org/

**Comment by nsf** [comment]
What tag should I add exactly? Are there any guides?

**Comment by nsf** [comment]
Oh, never mind, I see.

**Comment by nsf** [comment]
I've added this tag: https://github.com/nsf/gocode/tree/v.20150303 , should be enough?

**Comment by nlamirault** [comment]
According to Melpa maintainer, Melpa don't recognizes this tag [1].

[1] : https://github.com/milkypostman/melpa/issues/2553

**Comment by nsf** [comment]
http://stable.melpa.org/#/go-autocomplete
