### ISSUE TITLE
company-go backend isn't automatically loaded by company

### ISSUE THREAD

**Issue by bjoernpollex** [nsf/gocode#275]
The installation instructions for company-go say that company loads every backend it has by default. This didn't work for me. Only after adding the hook described in the same document the backend actually started working.

Either I have done something wrong (which is entirely possible), or the documentation is incorrect here, or there is a bug. Can someone clarify?

**Comment by nsf** [comment]
Have no idea, I'm not following company-mode development really. Maybe it was true before and now it is not. Maybe I was wrong. I really don't like elisp, and if I can avoid touching it - I do. :D So, if someone can clarify this issue I'd be more than happy.

**Comment by dgutov** [comment]
> Maybe it was true before and now it is not.

Nothing has changed in that regard for years.

**Comment by nicot** [comment]
@dgutov What should we say in the readme so that users know how to configure the backend?

**Comment by dgutov** [comment]
[company-irony](https://github.com/Sarcasm/company-irony#configuration) has a good example.
