### ISSUE TITLE
Access to server via HTTP

### ISSUE THREAD

**Issue by ekfriis** [nsf/gocode#279]
Hello,

Thank you for the awesome tool, it really makes my life a lot better.

I'm working on added direct support for gocode into YouCompleteMe (Valloric/ycmd/pull/106). Right now the YCM server daemon shells out to the gocode binary. If possible, I'd like to query the gocode server directly to avoid the overhead of spawning the subprocess + serialization etc. 

As far as I can tell, there is no way to connect via Python to the "net/rpc" used in gocode - please correct me if I'm wrong. Ideally I'd like to query the gocode server via JSON over HTTP. Would you be open to accepting a pull request implementing this?

Thanks!
Evan

**Comment by nsf** [comment]
Is there any reason why you find the process spawning overhead unacceptable? With hot file cache it's less than a millisecond probably (due to Go's static linking).

**Comment by ekfriis** [comment]
I think the concern is the overhead on constructing the subprocess on the python side, but you are right, this might be a premature optimization. I will measure the breakdown of the latency and see how much we would gain - if it's significant, I'll reopen.

Thanks!

**Comment by mackristof** [comment]
Hello,
I want to add the same http support for ace ( https://github.com/ajaxorg/ace/ ) golang completion plugin. is it preferable to create golang http service who spawn gocode ? or is it possible to start gocode with http handler ?

**Comment by nsf** [comment]
Gocode doesn't have that built-in, so.. one of two options:
1. Make a proxy which redirects requests from http to gocode daemon via gocode client.
2. Hack gocode and add http server support.

I would accept a patch which adds http daemon support to gocode (via additional command line flag).
