### ISSUE TITLE
Autocomplete stops working after importing "net" or "net/http"

### ISSUE THREAD

**Issue by hojgr** [nsf/gocode#284]
Hello,

i've been having issues with autocomplete feature. With this code
package main

package main

```go
import "fmt"

func main() {
	fmt.Println("Hello world")

}
```

Autocomplete works fine. After I write `fmt.` all fmt options pop up. But after I import package "net", nothing works anymore.

```go
package main

import "fmt"
import "net"

func main() {
	fmt.Println("Hello world")
}
```

With this code, if I do `fmt.` or `net.`, nothing shows up. Also, in the "notification area" on bottom I see `-- User defined completion (^U^N^P) Pattern not found`

Am I writing Go wrong way?

**Comment by nsf** [comment]
What editor are you using? I assume it's vim. What plugin is it? Is it gocode's plugin or some third party one? Seems like you're also using YouCompleteMe. Try invoking autocompletion manually with `C-x C-o` and see if it works.

**Comment by hojgr** [comment]
It is vim with plugin vim-go. I tried using `C-x C-o` too. After a little bit of trying to get it work I found out that using `gocode` alone yielded PANIC output. I've removed all of Go from my computer and installed it again, this time recommended way (downloading binaries from Golang.org instead of using package manager.)

It's working now. If I had to guess my versions didn't match.
