### ISSUE TITLE
Jump to definition of a specific implementation of interface functions

### ISSUE THREAD

**Issue by abourget** [nsf/gocode#286]
Often I want to debug an interface, but I'm really debugging one of its implementations..

When I look at code that calls funcs on that interface, and I jump to definition, I jump to the `type` definition.. Would it be possible to inject in the running `gocode` that I want to dereference jumps to that interface to a specific implementation ?

that'd be so awesome!

thanks

**Comment by nsf** [comment]
Well, gocode doesn't even provide "jump to definition". If an editor you're using provides such feature it's not implemented via gocode. It's not a hard thing to do, but it's not in gocode and I don't think I'll add that stuff anytime soon.

**Comment by abourget** [comment]
Whoops! sorry, I think it uses `godef`.. wrong project !
