### ISSUE TITLE
RuntimeError: Gocode shell call failed

### ISSUE THREAD

**Issue by tthanh** [nsf/gocode#290]
I'm using gocode with vim 7.4 and vim-go, YouCompleteMe plugin.
![screenshot from 2015-08-05 20 15 56](https://cloud.githubusercontent.com/assets/8962973/9086476/e14f5756-3bae-11e5-822b-ceae4699c775.png)
When I run `gocode -s` it's output `unix socket: '/tmp/gocode-daemon.mon' already exists`. I remove that file but gocode still not working in vim

**Comment by nsf** [comment]
I don't know what vim-go does.

After removing the socket file, try running gocode daemon in debug mode and see what it prints when you do requests from vim:
```
rm /tmp/gocode-daemon.mon
gocode -s -debug
```
<do an autocompletion request in vim, see what gocode daemon prints>

**Comment by tthanh** [comment]
Sorry for noob question but how can I do that? After running gocode -s -debug, I can only open vim in another tab or terminal, when I do an autocompletion, nothing show in gocode debug

**Comment by nsf** [comment]
Does autocompletion work or it shows the same error? What `which -a gocode` says?

Usually wrong things happen when setup is messed up. When you have multiple go versions installed at the same time or multiple gocode binaries or something along those lines.

**Comment by tthanh** [comment]
It's still show same error.
`which -a gocode`: `/home/mon/workspace/go/bin/gocode`
I'm install all go binaries in workspace folder

**Comment by nsf** [comment]
What `go env` says?

**Comment by tthanh** [comment]
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mon/.gvm/pkgsets/go1.5beta3/global:/home/mon/workspace/go"
GORACE=""
GOROOT="/home/mon/.gvm/gos/go1.5beta3"
GOTOOLDIR="/home/mon/.gvm/gos/go1.5beta3/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by nsf** [comment]
So you are using gvm also as I can see there. Oh man..

Well, if autocompletions do not work, then gocode doesn't look into the right place. There is no magic in it. Gocode client uses environment of the parent process (your vim editor) and it passes it to the gocode server.

So, in your vim session, take a look at `:!env` listing and see if there is a GOPATH in it and maybe some other GO* variables and do they match `go env`?

**Comment by nsf** [comment]
Also, the fact that vim prints "Gocode shell command failed" is something I wasn't paying attention too. It means that YouCompleteMe actually fails to execute gocode binary. I've found that error text in YouCompleteMe exactly and not somewhere else. Comes from here: https://github.com/Valloric/ycmd/blob/master/ycmd/completers/go/gocode_completer.py#L169

So, maybe vim doesn't even see gocode binary. Have you added gocode's binary location to PATH env var?

**Comment by nsf** [comment]
In other words..

In vim as I said earlier do `:!env` and the PATH that shows up there should contain `/home/mon/workspace/go/bin`. If that's not true, fix your env vars.

**Comment by tthanh** [comment]
I added gocode's binary location to PATH env. Everything like goimports or some binaries downloaded by vim-go work well with vim. I checked `:!env` in VIM and PATH have `/home/mon/workspace/go/bin`.

**Comment by nsf** [comment]
Well, if it still doesn't work, I'm out of ideas for now.

**Comment by nsf** [comment]
A good idea would be to try some simple editor like: https://github.com/nsf/godit. It has no settings at all, but it supports gocode. The only thing to keep in mind that it will be triggered for a *saved* file. Unsaved file has no file extension and hence gocode doesn't know that it's a go file. If gocode works with godit, then the problem is with vim setup somewhere.

**Comment by tthanh** [comment]
I just remove gocode binary in `/home/mon/workspace/go/bin` and reinstall it in `/home/mon/.gvm/pkgsets/go1.5beta3/global/bin`, gocode work again with vim.

**Comment by nsf** [comment]
good

**Comment by tthanh** [comment]
I think main reason of my bug is I didn't compile YouCompleteMe with flag `--gocode-complete`. After update YCM, gocode broke again so I found other solution on YCM page and recompile with gocode flag, everything work fine now. Thank you for support.
