### ISSUE TITLE
error with shared library

### ISSUE THREAD

**Issue by zmnpl** [nsf/gocode#292]
Hi,

I'm getting this error when running gocode:
    gocode: error while loading shared libraries: libgo.so.7: cannot open shared object file: No such file or directory

Regards
Simon

**Comment by nsf** [comment]
How do you build gocode? Shared libraries is a new Go feature or a gccgo feature. And well, I don't see how it is specific to gocode. If gocode binary is built against the shared go library and can't find it. Other go binaries will behave the same.

**Comment by zmnpl** [comment]
You are right. Somehow I had an old binary installed which was used instead of the freshly build ones. After figuring that out, deleting it and doing a fresh build it ran fine. Sorry for bothering you with my faults! (It was late (= )
