### ISSUE TITLE
Company-go sometime doesn't work with lastest commit.

### ISSUE THREAD

**Issue by ntcong** [nsf/gocode#294]
The commit adab99b939af07505b5c0c9ed117db9a7ce2f79e brokes company-go sometimes:

```
Company: An error occurred in auto-begin
Company: Back-end company-go error "End of file during parsing" with args (prefix)
```

I tried revert the commit and it works as normal.

I'm trying to edit the example qmlscene in go-qml/qml repo, go to line 23 and input `engine.` and the error appear

**Comment by nsf** [comment]
Can you please give me a link to the exact file you were testing it on?

**Comment by ntcong** [comment]
https://github.com/go-qml/qml/blob/v1/examples/qmlscene/qmlscene.go

This file, I added a line on line 22.

- Using `qml.`, it works as expected.
- Using `engine.`, company-go throws an error.

I'm on OSX btw.

**Comment by syohex** [comment]
I cannot reproduce this issue with latest `company` and `company-go` on Emacs 24.4(Ubuntu 15.04).

![output](https://cloud.githubusercontent.com/assets/554281/9433214/ec163f78-4a69-11e5-9829-00d7e623803b.gif)

**Comment by nsf** [comment]
Same. Can't reproduce it. Can you give us more info on versions you're using? Emacs? Company-mode?

**Comment by ntcong** [comment]
I'm on Emacs 24.5, company-mode  20150727.1415
I tried same setup on Ubuntu, doesn't have the problem. So maybe it's a rare case on OSX ?

![company-go](https://cloud.githubusercontent.com/assets/167336/9434311/952d6be8-4a67-11e5-8208-d4ab0a97629d.gif)

**Comment by nsf** [comment]
Maybe some other plugin breaks it? I can suggest trying it on a clean emacs with minimal `init.el`. Sadly I don't know much about elisp and how you actually debug it. Trying to minimize my time spent with elisp as much as possible. I like emacs, but elisp is just a broken thing (as all other typeless scripting languages) with ugly syntax.

**Comment by ntcong** [comment]
I'm not so good with elisp either, so I hope someone can point me to the right direction to debug.

In the meantime, revert the commit actually fixes the problem

**Comment by syohex** [comment]
Could you retry after reinstalling company, company-go ? You may use old byte-compiled file. I think that company-go--in-num-literal-p(added at adab99b) never raises exception(because company-grab-word always returns string, so string-match-p always succeeds), and adab99b change is not related to this issue.

**Comment by ntcong** [comment]
I tried but no sucess. I remove the commit and recompile and the problem is gone, add the commit again and recompile, the problem reappears.

Maybe the commit affects other part of the plugin, I'm not really sure

**Comment by ntcong** [comment]
in company-go--in-num-literal-p, there's a chance that company-grab-word  will return nil, and when it return nil, the problem occurred

**Comment by syohex** [comment]
Sorry I misread company-grab-word code. Could you check return value of `(company-grab-word)` when you get error ?

**Comment by TheBB** [comment]
Hi guys, I was talking with @ntcong on the Spacemacs gitter to help solve this. I just submitted #295. Since I can't reproduce the issue (no OSX) and don't use Go myself I haven't tested it but at least it's out there.

**Comment by ntcong** [comment]
I can confirm that it's fixed with the PR
