### ISSUE TITLE
gocode not obeying GO15VENDOREXPERIMENT

### ISSUE THREAD

**Issue by kylewolfe** [nsf/gocode#296]
I believe gocode should show code hinting for packages built from /vendor when GO15VENDOREXPERIMENT=1

**Comment by nsf** [comment]
As variable name suggests. It's an experimental feature. I'd rather wait.

**Comment by kylewolfe** [comment]
Mind pointing me in the right direction so I can make the update in a fork and move on with the 1.5 vendor experiment?

**Comment by nsf** [comment]
It's an interesting question. Technically gocode uses "go/build" library, which has a feature for resolving an import path to an actual physical path. But as far as I understand with vendoring, you also need to pass in additional input and that input is the package you're working with. Because the vendor directory you're looking for is located inside that package (or in one of the parent packages). Sadly "go/build" doesn't expose any kind of interface for GO15VENDOREXPERIMENT right now. Which in turn means that if you want to add vendoring feature you need to reimplement it all yourself. I see some code related to that in Go here: http://golang.org/src/cmd/go/pkg.go.

As for gocode, that's the main function which is responsible for package lookup: https://github.com/nsf/gocode/blob/master/declcache.go#L256

It gets called through that place: https://github.com/nsf/gocode/blob/master/autocompletefile.go#L65

And from here: https://github.com/nsf/gocode/blob/master/declcache.go#L110

First is the current file, second is where other files of the current file end up being.

So I guess you also need to pass the filename (as gocode sees it) of the request. Which is an implicit package dir as well. That's the main entry of the autocompletion request: https://github.com/nsf/gocode/blob/master/autocompletecontext.go#L229

**Comment by nsf** [comment]
Although build.Context propagation is implemented horribly via global variables here: https://github.com/nsf/gocode/blob/master/server.go#L141-L142.

So I guess something similar can be done with the filename.

Gocode isn't pretty at all.

**Comment by kylewolfe** [comment]
I have not had a chance to dig in to gocode to understand how it works yet. I see there is a recent merge request around import paths (https://github.com/nsf/gocode/pull/293/files#diff-4251f3baf4c835986bdf8837ce2469faR268). Is this where I could add in the current lib paths (g_config.LibPath?) vendor directory?

**Comment by nsf** [comment]
Well, somewhere in that function yes. But what if Go devs add vendoring to the "go/build" library later? That's why I don't want to implement it just yet.

**Comment by kylewolfe** [comment]
Do you mean permanently, and not guarded by the GO15VENDOREXPERIMENT os variable? If that does happen, is your current code ready for that?

If gocode gets an update for this, it should behave the same way the go build tool works. The vendor directory is only used as priority if GO15VENDOREXPERIMENT=1. This ensures those who are not using it, are not affected by the code change within gocode. So you're covered there.

**Comment by nsf** [comment]
Yes, because it's an experiment. But Go devs may enable it as default in 1.6, who knows. Also I may not accept patch with GO15VENDOREXPERIMENT=1. I thought I was rather clear with that point. An experimental feature is not meant for broad adoption.

**Comment by kylewolfe** [comment]
For those who find this looking for 1.5 vendor support, you can explicitly add each project to gocodes lib-path setting.

```
gocode set lib-path "$GOPATH\pkg\$GOOS_$GOARCH\project1\path\vendor:$GOPATH\pkg\$GOOS_$GOARCH\project2\path\vendor"
```

**Comment by nsf** [comment]
FYI: Added gb-specific lookup rules to gocode. See new config option in gocode: *package-lookup-mode*.

It's unclear for me what to if user wants to do tag-based builds or use other options such as enabling race detection.

Right now gocode supports only basic GOOS-GOARCH combination. https://github.com/constabulary/gb/commit/9f933632970a5b7a93460ed6dbb3ed5b4364a1c7

**Comment by nsf** [comment]
I don't know why I'm telling it to you though. IMHO Go doesn't do it right with vendor experiment. Gb does it better.

But also I meant to post this message to this pull request: https://github.com/nsf/gocode/pull/293

Sorry for bothering you.

**Comment by nii236** [comment]
@kylewolfe: Does your workaround work for files in the `/src/` folder also? Setting:
```
$ gocode set lib-path "$GOPATH/src/github.com/nii236/project1/vendor"
```
Does not result in working gocode for me.

**Comment by nsf** [comment]
@nii236 When it comes to imported packages, gocode doesn't look into their source code at all. It only uses `.a` files, which are compiled packages.

**Comment by mattfarina** [comment]
For what it's worth, the current plan is to enable the GO15VENDOREXPERIMENT by default in Go 1.6. In 1.6 it can be turned off. The plan is for no off switch in Go 1.7.

When Go 1.6 has it on by default will gocode support it?

**Comment by nsf** [comment]
Yes. Gocode will always support whatever go tool does. I just didn't want to rush it in.

**Comment by kylewolfe** [comment]
FYI - https://github.com/golang/go/issues/12278 has been added to milestone 1.6early, which will add the functionality to go/build.

**Comment by nsf** [comment]
Thanks for note. Having this functionality in "go/build" will make things easier for me (I guess).

**Comment by ryanwalls** [comment]
I know I would be interested in seeing support in `gocode` for the vendor experiment on parallel with what `go` has.  i.e.  Go ahead and look at the flag and change behavior if that environment variable is set.  

Now that I have vendoring, I don't really want to undo it to get code completion.  

Thanks for all you do to make this tool great!

**Comment by nsf** [comment]
I'll consider looking into the issue and maybe solving it before Go 1.6 release. Maybe this weekend.

**Comment by nsf** [comment]
Sorry, had no time. This weekend it's 100% I'll be working on gocode. However, whether I implement this feature or not, I cannot tell. Stay tuned. :)

**Comment by mattfarina** [comment]
@nsf thanks for keeping us updated.

**Comment by kylewolfe** [comment]
FYI - Moving vendor functionality from cmd/go to go/build has missed the 1.6 deadline (https://groups.google.com/forum/#!topic/golang-dev/_ZkIjgugqkI)

**Comment by nsf** [comment]
@kylewolfe Thanks for letting me know. And as you can see this feature is still not there. But I remember about it. One way or another I'll implement it shortly after Go 1.6 or maybe before the release. Just not very high on my priority list. I use `gb` myself mostly.

**Comment by mattfarina** [comment]
In Glide we managed to make it work by faking it with `go/build`. You can see the functionality [here](https://github.com/Masterminds/glide/blob/94bbd52c9c6d2735601d7ed900e7550f1e1ac16a/cmd/guess_deps.go#L53).

**Comment by nsf** [comment]
Thanks, I'll take a look.

**Comment by nsf** [comment]
https://github.com/nsf/gocode/commit/014025c6d32cd1bf4d508b6e067ee520842985dc

Implemented it here as a hack. You don't need to set GO15VENDOREXPERIMENT=1 for gocode in any way. It pretends that this option is enabled all the time. The worst problem you can get into is after enabling it first, compiling few vendor packages, then disabling it and using normal packages. In this case gocode will still use vendored packages. But I hope people don't do that.

The logic is rather simple at the moment. When you work on package under path "X" (gocode tries to figure that out) and importing package under path "Y", gocode will try to import it as "X/vendor/Y" first and only if it fails it will look for "Y".

On my super simple test package it works. Let me know if it works for you as well.

**Comment by nsf** [comment]
I've also made it recursive. If you edit package under path "a/b/c" and import package using path "Y", gocode will look for:

"a/b/c/vendor/Y"
"a/b/vendor/Y"
"a/vendor/Y"
"vendor/Y"
"Y"

A good example is "net" package in current Go master, which uses vendored "golang.org/x/net/http2/hpack".

**Comment by madhead** [comment]
I've used glide to vendor a few packages. `gocode` is still unable to help me with autocompletion (tried `cache-clean` and `stop`). My code is [pretty simple](https://github.com/madhead/saberlight/tree/developing/app). Also, I've tried to step into each of vendored libs and do a `go build` there. That created proper `*.a` files, like `$GOPATH/pkg/linux_amd64/github.com/madhead/saberlight/app/vendor/github.com/paypal/gatt.a` but `gocode` still doesn't resolve `gatt` as a package.

**Comment by nsf** [comment]
Works for me:

![gocodegocode](https://cloud.githubusercontent.com/assets/12567/12524643/4f415316-c180-11e5-8cce-4261ec201eea.png)

Try something: 

1. Update gocode: `gocode close && go get -u github.com/nsf/gocode`
2. `which -a gocode` - Possible mess with gocode binaries? Should show only one
3. Try running `gocode close && gocode -s -debug`, do autocompletion and see what it says about your package. It will show you environment as it sees it and whether the package was found or not.
4. Look at `gocode set` options. Make sure that `gocode set lib-path ""` is empty and `gocode set package-lookup-mode go` package lookup mode is set to Go.

If nothing helps, paste as much of the output from these steps above as you can here, I'll take a look.

**Comment by madhead** [comment]
1. Updated `gocode`, but looks like I used latest version
2. `$ which -a gocode = /home/madhead/Projects/go/bin/gocode`, single entry
4. `lib-path` was set to `$GOPATH`, but I edited `~/.config/gocode/config.json` to make it empty.
3. So, I started `gocode close && gocode -s -debug` and tried two autocompletions (via Atom). [Here is the log](https://gist.github.com/madhead/c8b0cdd0c7875b37203f)

**Comment by nsf** [comment]
You're editing a project outside of GOPATH:

> Got autocompletion request for '**/home/madhead/Projects/saberlight**/app/saberlight.go'

> GOPATH: **/home/madhead/Projects/go**

As a result gocode fails to figure out a GOPATH-relative path of your current project:

> Go project path: .

Go vendoring feature doesn't imply you can put your projects outside of GOPATH.

**Comment by madhead** [comment]
Thank you! You're absolutely right. My project was symlinked inside `$GOPATH`, but I opened editor inside projects directory, not inside `$GOPATH`. Everything works like a charm now!

**Comment by dobegor** [comment]
@nsf why is this issue is still opened then?

**Comment by kylewolfe** [comment]
As the issue creator, I'm now out of the loop as far as this issue goes, so I won't close this unless nsf feels that it has been addressed.

**Comment by nii236** [comment]
@kylewolfe: Just tested it, works perfectly. You just have to make sure your vendored dependencies have been built with `go build` (or in my case, `glide rebuild`).
