### ISSUE TITLE
Slow/Choppy while writing on Windows emacs

### ISSUE THREAD

**Issue by wildex999** [nsf/gocode#302]
I'm running emacs 24.5.1 on Windows 7, and Go 1.5.

I have go-mode installed through package manager, and added in .emacs with:
(require 'go-mode-autoloads)

I then followed the instruction for using "go get" to install GoCode(Tried both with and without the windows specific flags)

I have installed auto-complete-mode, also through package manager, and then I followed the readme instructions for adding the 'require's to the .emacs.

The problem I have is that whenever I write something that causes a gocode lookup, the whole emacs hangs for 1 to 2 seconds, pretty much making it unusable.

I notice in my process explorer that every time emacs hangs, it boots up a new gocode.exe and then terminates it, while another one seems to hang around all the time.

Is there something I have done wrong? How can I fix this? From what I see in videos, there should not be any hangup while writing code =/

The code I'm testing with is just this:
```
package main

import "fmt"

func main() {
	fmt.Printf("Hello, world.\n")
	fmt.Printf("")
	fmt.Printf("")
	fmt.Printf("")
	fmt.
}
```

Edit: Also, opening gocode.exe in a cmd window will start a new process, but the window will return without printing anything. Not sure if this is correct behavior?

**Comment by nsf** [comment]
Okay, this is a second windows-related report. First one was with spacemacs here: https://github.com/nsf/gocode/issues/297.

I'll definitely take a look on it tomorrow and I'll say if there are any problems. I haven't tried it on windows with Go 1.5.

**Comment by wildex999** [comment]
Thank you for the fast response =)

I just removed Go 1.5 and installed 1.4.2 to test if that would help
It runs flawlessly now, not even a hiccup while writing, and the autocomplete works as it should =)

So it does seems to be a Windows & Go 1.5 problem.

**Comment by nsf** [comment]
I confirm the bug, with Go 1.5 even in my own editor (godit), where I know exactly how it calls gocode, there is a very noticable delay on autocompletion request. I'll take a look where it comes from and see if I can solve it.

**Comment by nsf** [comment]
Should be fixed now by https://github.com/nsf/gocode/commit/c6fbdd52ff7382a15ac6. Please, take a look and if the bug is gone feel free to close the issue.

**Comment by nsf** [comment]
P.S. Don't forget to run `gocode close`. After `go get -u github.com/nsf/gocode`, to update the running daemon if any.

**Comment by wildex999** [comment]
Yup, now works perfectly =)
Thank you for the fast fix!
