### ISSUE TITLE
company-go cannot find gocode

### ISSUE THREAD

**Issue by CannedYerins** [nsf/gocode#303]
company-go seems to be failing to find gocode whenever I try to autocomplete.  For example, if I am partway through typing `flag.Parse()`, I get this:

```
Company: An error occurred in auto-begin
Company: backend company-go error "Searching for program: no such file or directory, gocode" with args (candidates Par)
```

I'm a bit confused as to why this is happening.  `M-x getenv PATH` yields

```
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/ian/go/bin
```

The last bit is indeed my $GOPATH/bin.  In eshell (which uses the emacs environment variables), `which gocode` indeed finds gocode:  `/home/ian/go/bin/gocode`.  So it seems like emacs can find gocode, but company-go somehow cannot.  

A bit of sanity check information:
- Everything is updated to the latest MELPA version.
- company-go is in `company-backends` while in go-mode.
- Relevant stuff from my init.el:
```
  (add-hook 'go-mode-hook 'company-mode)
  (add-hook 'go-mode-hook (lambda ()
                            (set (make-local-variable 'company-backends) '(company-go))
                            (company-mode)))
```

Any ideas about what I'm doing wrong?  Thanks!

**Comment by nsf** [comment]
That's weird indeed. Why do you have two hooks though? The second one enables company-mode as well. Maybe try removing the first one?

**Comment by CannedYerins** [comment]
Heh, I missed that.  Removing it didn't do anything though.

**Comment by nsf** [comment]
Hm. Can you try perhaps a different editor like godit: https://github.com/nsf/godit? If autocompletion works there, then the issue is emacs-specific for sure.

**Comment by CannedYerins** [comment]
Yes, when I used godit I was able to get autocompletion.

**Comment by nsf** [comment]
Yeah, I'm not suggesting replacing your editor, just checking. So, emacs then. For some reason it doesn't see code. Which OS are you using btw?

**Comment by CannedYerins** [comment]
Debian Linux.

**Comment by nsf** [comment]
Hm, that's interesting indeed. Usually on linux things go pretty smoothly. I wonder if you can try various options maybe like running emacs inside a terminal? `emacs -nw`. Or do you run it inside the terminal usually? Will it work there? Also it's possible that some other plugin somehow overrides the way emacs looks for binaries. Debugging emacs stuff isn't my thing really. You can try running gocode directly from emacs: http://www.gnu.org/software/emacs/manual/html_node/emacs/Shell.html

E.g. something like `gocode status`. And see if it works or not.

**Comment by CannedYerins** [comment]
Now this is interesting.  In all pairings of standalone emacs and `emacs -nw` with `M-x shell` and `M-x eshell`, `gocode status` works.  And it even shows information relating to my files that I was editing in an attempt to get this to work.  So clearly gocode is fine here.  

I usually run emacs as the standalone application, and I'm having the problems I've described here in that version.  But in `emacs -nw`, the company-go autocompletion works.  So somehow company-go is unable to find gocode only in the standalone emacs.  Scary.

**Comment by nsf** [comment]
Well, it's not scary. `emacs -nw` is executed via shell, but standalone is not. Different environment variables perhaps. Or something else is different. There's also some thing called exec-path in emacs, take a look here: https://github.com/purcell/exec-path-from-shell. Also in emacs take a look at `C-h v exec-path`

**Comment by CannedYerins** [comment]
Using exec-path-from-shell seems to have fixed this problem!  Thanks for pointing out this very useful package.  I'm not sure what was incorrect about my emacs PATH in the first place; I had set it manually so that (I thought) it was the same in emacs as in bash.  Regardless, that package fixed my error.  

Thanks very much for your debugging help, especially since this turned out to not be related to gocode or company-go in the end :(.  gocode is a great tool and I'm glad it has such a helpful owner!

**Comment by ReedRichards** [comment]
I'd like to add that I had a similar issue that was fixed from moving 
```
PATH=$PATH:$(go env GOPATH)/bin
GOPATH=$(go env GOPATH)
```
from my ~/.bashrc to ~/.profile
