### ISSUE TITLE
noob here: undefined packages while I install it

### ISSUE THREAD

**Issue by cocodrino** [nsf/gocode#309]
Hi, sorry I'm a bit newbie with go right now and I'm trying install gocode, I just install go using apt-get (I'm using elementary luna) then I run the installation of gocode and get

```bash

# github.com/nsf/gocode
/usr/lib/go/src/pkg/github.com/nsf/gocode/autocompletefile.go:16: undefined: parser.AllErrors
/usr/lib/go/src/pkg/github.com/nsf/gocode/autocompletefile.go:69: undefined: parser.AllErrors
/usr/lib/go/src/pkg/github.com/nsf/gocode/utils.go:209: ctx.ReleaseTags undefined (type *build.Context has no field or method ReleaseTags)
/usr/lib/go/src/pkg/github.com/nsf/gocode/utils.go:210: ctx.InstallSuffix undefined (type *build.Context has no field or method InstallSuffix)
/usr/lib/go/src/pkg/github.com/nsf/gocode/utils.go:225: unknown build.Context field 'ReleaseTags' in struct literal
/usr/lib/go/src/pkg/github.com/nsf/gocode/utils.go:226: unknown build.Context field 'InstallSuffix' in struct literal

```

I set the  $GOPATH 

```zsh


export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=~/Downloads/proj/goprojects
export PATH=$PATH:$GOPATH/bin



```
thank so much!!!

**Comment by nsf** [comment]
Could be an old version of Go. My suggestion is to avoid package managers and install it directly into your home dir: https://golang.org/doc/install. Preferably via directly cloning the official git repository, but since Go 1.5 installation from source became tricky. But hey, it's not a music player, you are a new or future software developer - figure this out.

**Comment by nhooyr** [comment]
Why is `GOROOT=/usr/local/go` if you installed with a package manager?

**Comment by nsf** [comment]
No response and it's not a gocode issue most likely, closing it.
