### ISSUE TITLE
Why gocode don't complete Go keywords even set propose-builtins to true

### ISSUE THREAD

**Issue by stardiviner** [nsf/gocode#312]
some Go keywords completing doesn't supported by gocode (in Emacs):

- import
- func
- etc ....

Even I config gocode with `$ gocode set propose-builtins true`. Still don't complete.

**Comment by nsf** [comment]
Gocode never completes keywords.

Built-ins are predefined functions/types/variables. You can see all of them here: https://golang.org/pkg/builtin/

And in gocode: https://github.com/nsf/gocode/blob/master/decl.go#L1316-L1396

**Comment by stardiviner** [comment]
Thanks @nsf

**Comment by DrGo** [comment]
Any reason why keywords are not autocompleted?

**Comment by nsf** [comment]
Because nobody implemented that.

**Comment by DrGo** [comment]
Fair enough,
how can I help implement them?
