### ISSUE TITLE
Not starting on Windows 10

### ISSUE THREAD

**Issue by Agnikay** [nsf/gocode#313]
I've used GoCode with Windows 8 and it was working perfectly! But once i got update on windows 10 GoCode even not starting. GoClipse stucks when trying to start GoCode server. CMD also stucks on running gocode. I've reinstall both GoCode and Golang and result the same.

*Update* The same behaviour reproduced with any executable build by go build. Simple "Hello, world" stucks as well, so seems problem not related to gocode itself 

Go env output:
GOARCH=amd64
GOBIN=
GOEXE=.exe
GOHOSTARCH=amd64
GOHOSTOS=windows
GOOS=windows
GOPATH=D:\MC\Go
GORACE=
GOROOT=D:\Go
GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
GO15VENDOREXPERIMENT=
CC=gcc
GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
CXX=g++
CGO_ENABLED=1

**Comment by nsf** [comment]
Can't help you, I don't use windows 10, maybe someone else will.

**Comment by hut8** [comment]
Unfortunately, I'm on Windows 10 and recently set up all this stuff and it seems to work fine, including starting the gocode daemon. I think this can be closed.

**Comment by shurcooL** [comment]
Yeah, OP edited the original post with:

> _Update_ The same behaviour reproduced with any executable build by go build. Simple "Hello, world" stucks as well, so seems problem not related to gocode itself

So it's a local setup issue, not gocode issue. Can be closed.
