### ISSUE TITLE
GOPATH is not evaluated (anymore)

### ISSUE THREAD

**Issue by dstpierre** [nsf/gocode#316]
On my console `echo %GOPATH%` returns the right path, but here's an output of log of `gocode -debug -s` after `gocode close`

```
2015/12/23 07:26:11 Import path "github.com/stripe/stripe-go" was not resolved
2015/12/23 07:26:11 Gocode's build context is:
2015/12/23 07:26:11  GOROOT: c:\go
2015/12/23 07:26:11  GOPATH:
2015/12/23 07:26:11  GOOS: windows
2015/12/23 07:26:11  GOARCH: amd64
2015/12/23 07:26:11  GBProjectRoot: ""
2015/12/23 07:26:11  lib-path: ""
```

So GOPATH is missing for some reason, but it is set: `echo %GOPATH%` => `d:\projects\go`

It just stopped working on my code editor like 2 days ago. I'm using vscode with the Go extension, but after some digging I realized that the GOPATH does not seems to be evaluated.

What should I do? The GOPATH variable is set at my user and my system level. The `go get` command is working fine. Any help would be apprecaited.

**Comment by nsf** [comment]
All I can tell is that GOPATH is passed from the client to server. Client is executed by your text editor usually. So make sure that the text editor has the right enviornment variable set.

> It just stopped working on my code editor like 2 days ago

My last commit is 12 days ago, so it wasn't me I guess.

Maybe VS Code stopped passing the environment to processes it executes? I don't know.

**Comment by dstpierre** [comment]
The extension is calling gocode like that:

```javascript
var p = cp.execFile(gocode, ["-f=json", "autocomplete", filename, "c" + offset], {
  env: {
  // Unset GOOS and GOARCH for the `gocode` process to ensure that
    GOHOSTOS and GOHOSTARCH 
    // are used as the target operating system and architecture. `gocode` is unable
to provide 
    // autocompletion when the Go environment is configured for cross compilation.
    GOOS: "",
    GOARCH: ""
  }
}
```

So `gocode` needs to have the GOPATH pass

**Comment by nsf** [comment]
No, here's the thing, they *unset* these variables. Which means there are default ones. If all environment variables are passed by default, then GOPATH should be amongst them. Hard to say, I'm not familiar with vs code.

**Comment by dstpierre** [comment]
excellent, I forked their code and added GOPATH and it works, so not sure how they are sending env var by default. But good news is it's definitely the plugin. 

Thank you for your time, highly appreciated.
