### ISSUE TITLE
gocode suddenly stopped updating.  How to debug?

### ISSUE THREAD

**Issue by bwmarrin** [nsf/gocode#317]
I'm fairly new to using gocode with vim for auto-completion so I could be doing something wrong.  I've been using it though for a couple months and it has been working great. The best thing I've added to my workflow ever :)

But, recently all of my changes to my go library (DiscordGo) have not been getting updated by gocode so when I work on a tool that uses the DiscordGo package auto-completion isn't working for new functions.

So far.

* I tried stopping the gocode process and letting it restart
* I tried using the command to clear the go-code cache
* I tried running gocode in debug mode but that didn't output anything.

I wanted to try an solve this on my own but I'm a bit lost what to check next.

**Comment by nsf** [comment]
Have you experimented with Go 1.5 vendoring feature? I've added vendoring support to gocode recently and it is always enabled and it's impossible to disable it. As a result if you've enabled vendoring once but don't use it anymore gocode may use out-dated libraries.

**Comment by bwmarrin** [comment]
Well.. Since I don't know what the vendoring feature is I'm guessing I haven't used it :)  But, I am also fairly new to Go (about 2.5 months now) so anything is possible.

**Comment by nsf** [comment]
Okay, then enable gocode's debug output:
```
gocode close
gocode -s -debug
```

It will show you which libraries it picks up for autocompletion. For example one of the lines after autocompletion request from a simple hello world example:
```
2015/12/29 21:12:01 Found "fmt" at "/home/nsf/go/pkg/linux_amd64/fmt.a"
```

It will print the same for your library. Then see whether it's the right file or not. What's its last modification timestamp, etc. Or paste everything here, I'll take a look. Also paste your `go env`.

**Comment by bwmarrin** [comment]
So, gocode -s debug doesn't seem to print anything for me.  For reference, I'm using gocode with Vim which was bundled in with the vim-go package (https://github.com/fatih/vim-go)

My go env is
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="freebsd"
GOPATH="/home/bruce/golibs"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GO15VENDOREXPERIMENT=""
CC="cc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

Also, it seems once I add one of the "missing" funcs into my program and compile the program it does update the auto-complete but I could swear it used to list anything that existed in my DiscordGo package as soon as I added it to those files.  Hopefully that makes sense.

**Comment by nsf** [comment]
Gocode uses compile libraries to extract semantic info for imported packages it never uses source file. It only parses source files of the currently edited package.

**Comment by bwmarrin** [comment]
Ah, well.  Sorry for my misunderstanding :)

But, if I have a package imported into a test program and build the test program, should it pick up all the funcs in that package after that? Or does it only pick up the functions I actually used at least once manually in that test program?  I suppose it makes sense that Go wouldn't add in the code for funcs not being used so I am guessing the answer is aligned with that.

**Comment by nsf** [comment]
If you `go install` it, it will build the dependencies (the packages) and gocode will pick it up. It will pick up all funcs defined in a package.

**Comment by nsf** [comment]
`go build` however, I think rebuilds dependencies always and never saves them. It will only produce a binary for a "main" package if you build it directly.

**Comment by bwmarrin** [comment]
Oh, that's great.  I just tried doing the "go install" on my package itself actually and it looks like everything is showing up actually.  I'll toy around to make sure but thanks a lot for the help. Also thanks for making gocode it saves me such a tremendous amount of time :)

**Comment by nsf** [comment]
Np.
