### ISSUE TITLE
Is this normal behavior?

### ISSUE THREAD

**Issue by wlaurance** [nsf/gocode#322]
According to `htop`

![screen shot 2016-01-28 at 6 27 45 pm](https://cloud.githubusercontent.com/assets/1059214/12665544/4d7346f4-c5ed-11e5-9971-3b86b824c4b1.png)

546.8 GB of VIRT

Seems like a lot of memory to me.

Is something strange happening?

**Comment by nsf** [comment]
I don't do anything special to increase virtual memory size. Yes, it can be normal. In general, garbage collected languages may consume a lot of virtual memory, depending on their implementation of memory management. The memory is virtual, so don't worry about it. Address space is rather big on 64 bit machines, there is enough of it for everybody.

But maybe you're using some weird Go version I don't know. On my machine gocode consumes just 100 megs of virtual memory right after launch.

In any case, gocode doesn't do much outside of a typical Go program, it just reads files, processes them and serves some data over TCP or UNIX socket.

**Comment by wlaurance** [comment]
I'm using `go version go1.5.3 darwin/amd64`. It ramps up to 546.8 on launch for me.

I just looked and all of my go (server/daemon) programs have that much VIRT memory.

Strange.

Thanks for the info.

Marking as closed!
