### ISSUE TITLE
Add support for GoTo

### ISSUE THREAD

**Issue by Manishearth** [nsf/gocode#323]
Many IDEs let you go to the definition of a variable, function, type, or whatever with some command. I've been using YouCompleteMe with Rust and Go and am missing this functionality from Go (the YCM Go port uses gocode).

I'm willing to try working on this, but I have some questions:

 - Is this something you'd want in gocode?
 - I tried my hand at this already, one issue is that files aren't named when fed into the parser (`AddFile()`). This means that the fileline information that `token.Position` can provide won't know about the file, so we only get line/column information with an empty filename. This isn't too useful. Do you know how to fix this? I don't get filenames for types from the main file (which makes sense since we don't name the main file when feeding it in), local package files, or even for gopath packages (which doesn't make sense since the parser figures this out itself AFAICT). I'm not sure how `FileSet` works so I might be missing something here.

Here's my testing code for reference (just trying to get the file thing to work, after that it's just hooking stuff up to RPC and some refactoring):

```diff
diff --git a/autocompletecontext.go b/autocompletecontext.go
index 6d636d7..a0a2f33 100644
--- a/autocompletecontext.go
+++ b/autocompletecontext.go
@@ -24,6 +24,7 @@ type candidate struct {
 	Name  string
 	Type  string
 	Class decl_class
+	Pos token.Pos
 }
 
 type out_buffers struct {
@@ -75,6 +76,7 @@ func (b *out_buffers) append_decl(p, name string, decl *decl, class decl_class)
 		Name:  name,
 		Type:  b.tmpbuf.String(),
 		Class: decl.class,
+		Pos: decl.Pos(),
 	})
 	b.tmpbuf.Reset()
 }
@@ -118,7 +120,6 @@ func (b *out_buffers) append_embedded(p string, decl *decl, class decl_class) {
 		}
 		b.append_embedded(p, typedecl, class)
 	}
-
 	if first_level {
 		// remove tmp namespace
 		b.tmpns = nil
@@ -298,12 +299,22 @@ func (c *auto_complete_context) apropos(file []byte, filename string, cursor int
 			c.get_candidates_from_decl(cc, class, b)
 		}
 	}
+
 	partial = len(cc.partial)
 
 	if len(b.candidates) == 0 {
 		return nil, 0
 	}
 
+	c.current.fset.Iterate(func(f *token.File)  bool {
+		fmt.Printf("- %v -\n", f.Name())
+		return true
+	})
+	for _,candidate := range b.candidates {
+		pos := c.current.fset.Position(candidate.Pos)
+		fmt.Printf("%v//%v = %v:%v:%v # %v \n", candidate.Name, candidate.Type, pos.Filename, pos.Line, pos.Column, pos.Offset)
+	}
+
 	sort.Sort(b)
 	return b.candidates, partial
 }
diff --git a/decl.go b/decl.go
index 69564ee..0b81754 100644
--- a/decl.go
+++ b/decl.go
@@ -97,6 +97,9 @@ type decl struct {
 	scope *scope
 }
 
+func (d decl) Pos() token.Pos {
+	return d.typ.Pos()
+}
 func ast_decl_type(d ast.Decl) ast.Expr {
 	switch t := d.(type) {
 	case *ast.GenDecl:
diff --git a/server.go b/server.go
index eecf1c8..b828504 100644
--- a/server.go
+++ b/server.go
@@ -4,6 +4,7 @@ import (
 	"bytes"
 	"fmt"
 	"go/build"
+	"go/token"
 	"log"
 	"net"
 	"net/rpc"
@@ -129,7 +130,7 @@ func server_auto_complete(file []byte, filename string, cursor int, context_pack
 		if err := recover(); err != nil {
 			print_backtrace(err)
 			c = []candidate{
-				{"PANIC", "PANIC", decl_invalid},
+				{"PANIC", "PANIC", decl_invalid, token.NoPos},
 			}
 
 			// drop cache
```

**Comment by myitcv** [comment]
@Manishearth have you seen [`godef`](https://github.com/rogpeppe/godef)?

**Comment by nsf** [comment]
Yes, I want it, but it's a complicated issue for gocode. Gocode parses compiled packages to get semantic info. And if you want to do proper cross-package development and jump between packages, gocode can't provide that at the moment. The proper way to do it is to parse source files in gocode, but it's unlikely that it happens soon, I have no time to implement that feature.

**Comment by Manishearth** [comment]
@myitcv Hm, I've seen it, but hadn't considered integrating it with YCM. I'll try.

@nsf thanks for the response! I'll probably try using godef first. Feel free to close :smile:
