### ISSUE TITLE
gocode allocs too much virt

### ISSUE THREAD

**Issue by gaocegege** [nsf/gocode#324]
I don't know what happened :worried: 
<img width="1032" alt="1" src="https://cloud.githubusercontent.com/assets/5100735/12846726/19eaddb2-cc49-11e5-8072-439482b346f4.png">

**Comment by shurcooL** [comment]
This might be normal (and harmless) behavior. See previous issue #322.

**Comment by gaocegege** [comment]
oh, sorry, got it~
