### ISSUE TITLE
File error: Cannot open load file, no such file or directory, go-autocomplete

### ISSUE THREAD

**Issue by tleyden** [nsf/gocode#325]
I'm trying to follow the instructions and update a [blog post](http://tleyden.github.io/blog/2014/05/22/configure-emacs-as-a-go-editor-from-scratch/) I wrote a few years ago on setting up emacs for go development, but I'm running into problems with gocode.  

I'm using [emacsformacosx](emacsformacosx.com) v24.5 and I'm installing `auto-complete` from melpa.

Here's my [complete emacs.d/init.el file](https://gist.github.com/tleyden/d3d129e9a791a25b262b)  

I'm installing gocode via:

* `go get -u -v github.com/nsf/gocode`
* `cp /Users/tleyden/Development/gocode/src/github.com/nsf/gocode/emacs/go-autocomplete.el ~/.emacs.d/`
* Add the following to `~/.emacs.d/init.el`

```
(require 'go-autocomplete)
(require 'auto-complete-config)
(ac-config-default)
```

When I start emacs I get:

```
Warning (initialization): An error occurred while loading `/Users/tleyden/.emacs.d/init.el':

File error: Cannot open load file, no such file or directory, go-autocomplete
```

Which seems like it's not finding the `/Users/tleyden/.emacs.d/go-autocomplete.el` file for some reason.  I tried explicitly adding `(add-to-list 'load-path "/Users/tleyden/.emacs.d/")` (shouldn't this be in the load path by default?), and now I get this error when starting emacs:

```
Warning (initialization): An error occurred while loading `/Users/tleyden/.emacs.d/init.el':

File error: Cannot open load file, no such file or directory, auto-complete

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
Warning (initialization): Your `load-path' seems to contain
your `.emacs.d' directory: /Users/tleyden/.emacs.d/
This is likely to cause problems...
Consider using a subdirectory instead, e.g.: /Users/tleyden/.emacs.d/lisp
```

(I tried to use the `.emacs.d/lisp` subdirectory as suggested but it didn't seem to change anything)

Any ideas?  

I did get this to work at one point using [these instructions to install auto-complete](https://github.com/tleyden/tleyden.github.io/blob/3f14c8dc5b9117240f35dc5cd2c5dcb7592d3e19/source/_posts/2014-05-22-configure-emacs-as-a-go-editor-from-scratch.markdown#autocomplete) rather than installing via melpa.  I wonder if upstream changes in the way auto-complete is packaged have caused compatibility issues?

**Comment by syohex** [comment]
Why didn't you install `go-autocomplete` from MELPA ? You can install `go-autocomplete` from MELPA(https://melpa.org/#/go-autocomplete).

You should add `(package-initialize)` in your configuration file. It sets load-pathes for packages which are installed by package.el(You should not set load-path for packages which are installed by package.el)

>  I tried explicitly adding (add-to-list 'load-path "/Users/tleyden/.emacs.d/") (shouldn't this be in the load path by default?),

You should not add `~/.emacs.d` to `load-path` because Emacs does not recommend it.

**Comment by tleyden** [comment]
> Why didn't you install go-autocomplete from MELPA ? You can install go-autocomplete from MELPA(https://melpa.org/#/go-autocomplete).

Thanks -- I'll try that!

**Comment by tleyden** [comment]
I installed `go-autocomplete` via melpa (`M-x package-install` followed by `go-autocomplete`) but it doesn't seem to be taking effect.  

**Expected**

<img width="448" alt="emacs_autocomplete" src="https://cloud.githubusercontent.com/assets/296876/12871387/9f77c876-cd2c-11e5-8702-c3d367de46b5.png">

**Actual**

<img width="1076" alt="emacs-go-autocomplete-not-working" src="https://cloud.githubusercontent.com/assets/296876/12871388/abf25cc4-cd2c-11e5-8153-a9c613298892.png">

What's the best way I can verify it's working?  Also, do I need to add anything to my `~/.emacs.d/init.el` after installing the melpa package?

Here is my [.emacs.d directory](https://gist.github.com/tleyden/3e2b1830eca52e921242#file-gistfile1-txt) and [~/.emacs.d/init.el](https://gist.github.com/tleyden/3e2b1830eca52e921242#file-init-el)

**Comment by syohex** [comment]
Please load `go-autocomplete`. Could you add following configuration to your init.el and retry ?

```
(with-eval-after-load 'go-mode
  (require 'go-autocomplete))
```

**Comment by tleyden** [comment]
@syohex that fixed it -- thanks!  Here's how I got it working .. 

Install the melpa package via `M-x package-install` followed by `go-autocomplete`

Add the following to your `~/.emacs.d/init.el` file:

```
(defun auto-complete-for-go ()
(auto-complete-mode 1))
 (add-hook 'go-mode-hook 'auto-complete-for-go)
```

Actually I'm not sure if I added that or whether this gets added automatically when installing `go-autocomplete`.  If it's already in your `~/.emacs.d/init.el` file then you can skip that.

You'll also need the following:

```
(with-eval-after-load 'go-mode
   (require 'go-autocomplete))
```

Now restart emacs, and when you start typing the name of a field in a struct it will popup something that looks like this:

![screenshot](http://tleyden-misc.s3.amazonaws.com/blog_images/go-autocomplete.png)
