### ISSUE TITLE
[emacs company] Could not complate at point

### ISSUE THREAD

**Issue by gozes** [nsf/gocode#326]
after setting up go-mode and company-go, company-go will not compleat at all and the gocode buffer is empty.

using Go 1.5 from the Arch Linux repository 
I installed gocode using go get 

How I came across the issue:
first setup GOPATH

```bash
export GOPATH=$HOME/.go:$HOME/Code/go
export PATH=$PATH:$GOPATH/bin
```
I like to separate the workspace and my go code. for that reason I append the path to where I keep all my go code to the GOPATH

then setup go-mode and company-go 

Here is how I have it setup:

```elisp
(use-package go-mode :ensure t :defer t)

(use-package company-go :ensure t :defer t
  :config
  (progn
    (setq company-tooltip-limit 20)
    (setq company-idle-delay .3)
    (push 'company-go company-backends)))

(use-package go-eldoc
      :ensure t
      :defer t
      :config
      (progn
        (add-hook 'go-mode-hook 'go-eldoc-setup)))
```
then I created a test package to test my setup

made  a directory/package and a source file  in that directory with the same name as the directory/package

then wrote this 

```go

package main 

func main(){
	fmt.
}

```
even if I explicitly import fmt I will still get no completion at all. Even typing .P will not get me any completions or get the company buffer to pop up.

**Comment by syohex** [comment]
Did you enable company-mode in go-mode or global-company-mode ?

**Comment by gozes** [comment]
@syohex  globaly because I use company for completion in all the programming modes I use.

**Comment by syohex** [comment]
I suppose you should set company-backends in go-mode-hook.

```lisp
(use-package go-mode :ensure t :defer t
  :config
  (defun my-go-mode-hook ()
    (push 'company-go company-backends))
  (add-hook 'go-mode-hook 'my-go-mode-hook))
```

**Comment by gozes** [comment]
@syohex  ok the company-go backend is working but I get an error saying that that it can't find the file or directory gocode with args (candidates)

'''go

package main 

import "fmt"
func main(){
	fmt.
}
``` I added the import to test if it was that but I get same error.

**Comment by syohex** [comment]
Did you set PATH environment variable and exec-path variable and can you see `gocode` from your Emacs ? `M-! which gocode` or `(executable-find "gocode")`.

**Comment by gozes** [comment]
@syohex  I have this on my bashrc 

```bash
export GOPATH=$HOME/.go:$HOME/Code/go
export PATH=$PATH:$GOPATH/bin
```

 but I can't see it from emacs but I do from the terminal. I haven't touch the PATH from anywhere in my emacs config

**Comment by syohex** [comment]
You need to set PATH and exec-path for using gocode. I recommend you to use [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell), you can load environment variables from your configuration file like `.bashrc` by it.

**Comment by gozes** [comment]
@syohex ok that got my PATH issue fix. Now, if I do a which from emacs it tells me that it can't find gocode but I see the path to my GOPATH in the output. and yes if I call gocode -h from the terminal it work fine.

**Comment by syohex** [comment]
You need to set `GOPATH`(and `GOROOT` if you install go in non-standard directory) environment variable as well as PATH.

**Comment by gozes** [comment]
@syohex I installed go from the arch repository so it will go in that same place as every other package in my system. /usr/lib/ fro libs and /usr/bin for binarys

**Comment by syohex** [comment]
Can you see GOPATH from Emacs ? What does `(getenv "GOPATH")` return ?

**Comment by gozes** [comment]
@syohex I get /home/gozes/.go:/home/gozes/Code/go but If I do executable-find for gocode  I get nil I even used exec-path-from-shell-copy-env  to make extra sure that GOPATH is set on my emcas

**Comment by syohex** [comment]
Does your path contain `$GOPATH/bin`(`/home/gozes/.go/bin` and `/home/gozes/Code/go/bin`)?

**Comment by gozes** [comment]
@syohex 
Yup that was the issue

before I had this on my bashrc
```bash
export GOPATH=$HOME/.go:$HOME/Code/go
export PATH=$PATH:$GOPATH/bin
```
if you have it set that way then the /bin part only gets added to the last entry on the GOPATH(my Code/go dir) but go get will put the src and bins that you download by default on the first entry on your GOPATH. 
So, if you like to separated things like I do then you will have to do the following 

now I have this
```bash
export GOPATH=$HOME/.go:$HOME/Code/go
export PATH=$PATH:$HOME/.go/bin:$HOME/Code/go/bin
```
and now it works just fine.

Seriously, why can go just put library you download under its system wide dir like every other language out there or just let the  developer chose where it wants stuff to go :anger: :anger:   

@syohex  thank  you so much for all your help.
you are really awesome :bow: :bow: :bow:

**Comment by nsf** [comment]
Problem solved it seems, reopen if not.
