### ISSUE TITLE
RuntimeError: Gocode returned empty JSON response.

### ISSUE THREAD

**Issue by elithrar** [nsf/gocode#340]
* Running gocode @ 3b7488f
* YouCompleteMe @ 21a0019
* vim-go @ fc682ce
* neovim stable 0.1.2

(all are the latest as of this post)

Sporadically (but often), attempting to autocomplete an identifier will return `RuntimeError: Gocode returned empty JSON response.` in neovim.

The closest issue I've found is https://github.com/fatih/vim-go/issues/531 - which doesn't wholly describe the problem/fix.

**Comment by nsf** [comment]
Hard to tell if that's gocode fault or not. Error definitely comes from neovim, so, have no idea what it does. Maybe it simply fails to handle no autocompletion results. Or an unlikely scenario when gocode returns nothing. Gocode is pretty fault tolerant, if it panics it drops the cache and returns "PANIC" as suggestion. So, I can't imagine a case when it returns nothing.

**Comment by elithrar** [comment]
OK: that does help debug (since I now know what to expect).

This happens often when I should have an autocompletion result—e.g. I had
suggestions for the same package/type moments before—which is why it is so
frustrating.

I suspect it is a conflict between YouCompleteMe, gocode & neovim.

**Comment by elithrar** [comment]
This is being generated by YouCompleteMe / ycmd @ https://github.com/Valloric/ycmd/blob/6df0fe50cacb8887eda0785b845e8dc049ca0408/ycmd/completers/go/go_completer.py#L40

It appears to be generated here when Python's `json.loads` returns a `ValueError` (e.g unmarshalling error) - https://github.com/Valloric/ycmd/blob/6df0fe50cacb8887eda0785b845e8dc049ca0408/ycmd/completers/go/go_completer.py#L125-L128

The panic case is handled separately: https://github.com/Valloric/ycmd/blob/6df0fe50cacb8887eda0785b845e8dc049ca0408/ycmd/completers/go/go_completer.py#L130-L136

This is probably worth reporting in ycmd, but is there anything about gocode's JSON that might trip up the `json.loads( ToUnicode( stdoutdata ) )` unmarshalling in Python?

**Comment by nsf** [comment]
The formatter is simple and I don't use proper json escaping, but results shouldn't really contain any special characters which require escaping: https://github.com/nsf/gocode/blob/master/formatters.go#L135-L152

Would be nice to see the output which produces invalid JSON if that's the case.

**Comment by elithrar** [comment]
Best way to trigger that (so that I can match the RuntimeError) - turn on gocode debug mode?

**Comment by nsf** [comment]
Trigger what?

**Comment by elithrar** [comment]
When `RuntimeError: Gocode returned empty JSON response.` is triggered by ycmd, is there a way to get the debug output from gocode to see what it was outputting?

**Comment by nsf** [comment]
Sadly, no. Formatting happens on the client side and debug flag only works on the server side. And messages in-between are sent using a binary format.

**Comment by nsf** [comment]
Okay, was looking at the ycmd issue mentioned here. It seems what gocode returns is not an "empty JSON response", but `[]`, which is a non-empty JSON reponse, but empty JSON array and hence a valid gocode output.

Closing it as it's not a gocode bug.
