### ISSUE TITLE
Add support for binary export format

### ISSUE THREAD

**Issue by mewmew** [nsf/gocode#347]
golang/go@7538b1d enabled the new binary export format by default. This broke code completion is Sublime, which uses `gocode` under the hoods as far as I know.

**Comment by kostya-sh** [comment]
Dup of #305

**Comment by nsf** [comment]
Yes, closing it as a dup. I'll take a look at the format this weekend.

**Comment by mewmew** [comment]
> Yes, closing it as a dup. I'll take a look at the format this weekend.

Wonderful! Thanks for taking a look at this, and sorry for the dup.
