### ISSUE TITLE
20 failed tests

### ISSUE THREAD

**Issue by nhooyr** [nsf/gocode#362]
When I run `./all.bash` in `_testing` I get 20 failed tests.

[results.txt](https://github.com/nsf/gocode/files/362339/results.txt)

**Comment by zchee** [comment]
@nhooyr Hi,
I don't test and only read results.txt, but maybe you set `propose-builtins: true`?
`all.bash` script is only run `gocode close`, clear in-memory cache but it does not have to return to the default settings.
https://github.com/nsf/gocode/blob/master/_testing/all.bash

@nsf Relatedly, I was considering the PR that introduce a travis test for pull-request.
What do you think?

**Comment by nhooyr** [comment]
@zchee You're correct. I have `propose-builtins: true`. The script should ensure gocode uses defaults when running tests. See PR #363

**Comment by nsf** [comment]
I don't think we need CI tests here. Gocode is not like an actively developer project and tests cover nothing really, just basics.

**Comment by zchee** [comment]
@nsf OK, I understood your intention well.
Thanks for the reply.
