### ISSUE TITLE
How can i set "ac-auto-start" for go-autocomplete in emacs

### ISSUE THREAD

**Issue by pzlvv** [nsf/gocode#366]
I want to pop up the prompt after entering 4 or more letters, I can set the ac-auto-start for other mode but it doesn't work for go-mode.

**Comment by syohex** [comment]
Overwrite `requires` parameter in go auto-complete source as below.

```lisp
(setf (cdr (assoc 'requires ac-source-go)) nil)
```

**Comment by pzlvv** [comment]
@syohex Can you describe more exactly? Here's the only segment I find in go-autocomplete source file contains `requires`

```lisp
(ac-define-source go
  '((candidates . ac-go-candidates)
    (candidate-face . ac-candidate-face)
    (selection-face . ac-selection-face)
    (document . ac-go-document)
    (action . ac-go-action)
    (prefix . ac-go-prefix)
    (requires . 0)
    (cache)))
```

**Comment by syohex** [comment]
`requires` property of auto-complete source is minimum length of starting completion. Its value `0` means that go-autocomplete always complete without user input. If its value is nil, then `ac-auto-start` is used.
