### ISSUE TITLE
RuntimeError: Gocode panicked with GO1.7

### ISSUE THREAD

**Issue by yangbinnnn** [nsf/gocode#370]
* go version go1.7 darwin/amd64 get runtime error blew

```
RuntimeError: Gocode panicked trying to find completions, you likely have a synt
ax error.
```
* go version go1.6.3 darwin/amd64 is OK

**Comment by nsf** [comment]
Try updating gocode first by running:

```bash
go get -u github.com/nsf/gocode
gocode close
```

And tell me if it helps.

**Comment by yangbinnnn** [comment]
Yes, It helps. THANKS A LOT. I forgot run `gocode close` before

**Comment by yangbinnnn** [comment]
I GET A NEW PROBLEM.
the autocompletion just work when i run gocode every time before i edit the source code.
Example:
```
gocode
vim hello.go # gocode work well
vim hello.go # reopen the hello.go, gocode not work，`fmt.` no tips
gocode
vim hello.go # I's OK again
```
I found the gocode process shutdown when i exit vim, I use gocode via vim-go plugin. Maybe I got wrong vim-go config. sorry for my problem
```
 501 48638     1   0  2:06AM ttys005    0:00.01 gocode -s -sock unix -addr 127.0.0.1:37373
```

**Comment by nsf** [comment]
Have no idea why this is happening.

**Comment by yangbinnnn** [comment]
Perhaps YCM with vim-go compatibility issues, but I'm not sure. I install they both and install YCM with --gocode-completer.

gocode work well after reinstall YCM and vim-go

THANKS.

**Comment by janbaer** [comment]
I still have the same problem. I'm running go1.7.1 darwin/amd64 and I updated gocode and also reinstalled YCM. What else can I check?

**Comment by nsf** [comment]
Look for other gocode binaries. YCM in fact uses a separate binary installed by itself as far as I know. Perhaps you need to remove its binary to force to rebuild. I don't know, never used YCM.

**Comment by janbaer** [comment]
Thanks for the tip, I completely removed the YCM folder then cloned it again from github including all submodules and run the install.py script and now it's working perfectly in VIM! :-)
