### ISSUE TITLE
gocode works strange with smb/sshfs on mac os X

### ISSUE THREAD

**Issue by Shmel1k** [nsf/gocode#371]
I have sshfs'ed some directory with pkg folder inside appeared after 'gb build' on remote machine. Gocode doesn't see autocompletions for that project. But when i use 'gb build' on local machine in this sshfs'ed folder, it finds everything. I haven't seen such issues in Ubuntu 16.04. Thnx in advance.

ps: package-lookup-mode "gb" and autobuild "true" are set. GOPATH is not set to that folder in ubuntu 16.04 either.

**Comment by nsf** [comment]
Have no idea why. I mean gocode doesn't do anything special with files,maybe some issues with mtime? If sshfs somehow hides or fakes modification time, cache may end up not reloading package files.

**Comment by Shmel1k** [comment]
The problem is missing darwin-amd64 folder in /pkg/, but linux-amd64 is present, that's why gocode can not use autocompletion. After 'gb build' on mac darwin folder appears and it starts working well.

**Comment by nsf** [comment]
Oh, so, the machine you ssh to and host have different OSes, that's obviously won't work. :) Technically gocode respects GOOS and GOARCH environment variables, so you can try that as an option, but it means you'll have to run gocode explicitly. So it might work, but I'm not sure.

**Comment by Shmel1k** [comment]
Thnx for your answer! :)
