### ISSUE TITLE
Instruction to install gocode with vim-plug doesn't work

### ISSUE THREAD

**Issue by motomux** [nsf/gocode#382]
I'm trying to install gocode with vim-plug as described on README.md, but I get the following error when I run `:PlugInstall` on vim.
`x Post-update hook for gocode ... Exit status: 1`

Versions
Vim: 8.0.2
Go: 1.7.1
Zsh: 5.2
OSX: 10.11.6

**Comment by nsf** [comment]
@ghiden added that readme instruction.

Feel free to fix it, both of you. I know nothing about vim-plug and can't help you.

**Comment by ghiden** [comment]
Hi @motomux 
I just upgraded my vim to 8.0.2 and clean install gocode.
It works fine.

Did you have gocode installed before you upgraded your vim to 8.0.2?
Try the following:
1. Open .vimrc and comment out gocode line
2. Run PlugClean and exit
3. Remove ~/.vim/autoload/gocomplete.vim
4. Remove the folder ~/.vim/ftplugin/go
5. Open .vimrc again, uncomment the gocode line
6. Run PlugInstall

**Comment by motomux** [comment]
Hi @ghiden 

Thank you for your instruction.

Your instruction works for me.
I tried just PlugClean and PlugInstall, and it was a problem.

Thank you
