### ISSUE TITLE
Some library can not complete in Vim

### ISSUE THREAD

**Issue by fcying** [nsf/gocode#388]
I'm using the github.com/therecipe/qt, 

It can be autocompletion in Atom+autocomplete-plus, but not work in Vim(the other library work ok)

the attachment is the log of  "gocode.exe -s -debug" in atom, vim and test file

[log.zip](https://github.com/nsf/gocode/files/493338/log.zip)

**Comment by nsf** [comment]
Well, log shows that in both cases gocode gives you a list of autocompletions. Not sure what's wrong with vim.

**Comment by nsf** [comment]
https://github.com/nsf/gocode/issues/389 - might be related if you're using YouCompleteMe in vim.

**Comment by fcying** [comment]
I test my plug, this is cause by neocomplete, use <c-x><c-o> can autocompletion.
May be the library too large lead neocomplete overtime.

Thanks  for the help~~
