### ISSUE TITLE
document for candidates for function company-show-doc-buffer

### ISSUE THREAD

**Issue by stardiviner** [nsf/gocode#393]
I found `company-show-doc-buffer` function does not show documentation for candidates.
Hope gocode can support it.

**Comment by nsf** [comment]
Gocode doesn't support showing docs. Err.. yet.

**Comment by stardiviner** [comment]
Will `gocode` support this?

**Comment by nsf** [comment]
Yes, but when is a good question. I wouldn't expect it this year.

**Comment by stardiviner** [comment]
I see. Hope someone will be interested in this feature.

**Comment by nsf** [comment]
Will close the issue as duplicate: https://github.com/nsf/gocode/issues/150
