### ISSUE TITLE
Binary files can not be called from spacemacs

### ISSUE THREAD

**Issue by zhexuany** [nsf/gocode#394]
Error info:
1. elder error: (file-error Searching for program No such file or directory gocode) 
2. Could not run godef binary 

I already set `GOPATH`. The result of `echo $GOPATH` is `~/repo/go`.

**Comment by nsf** [comment]
`gocode` binary needs to be available in PATH, add GOPATH/bin to your PATH.

`which -a gocode` should point to the right binary and there should only be one of them
