### ISSUE TITLE
Import path was not resolved

### ISSUE THREAD

**Issue by Spalf** [nsf/gocode#400]
Hi!

`2016/10/31 15:47:16 Go project path: .
2016/10/31 15:47:16 Got autocompletion request for` `'/Users/spalf/dev/golang/src/github.com/Spalf/pomodoroBot/main.go'`
`2016/10/31 15:47:16 Cursor at: 195`
`2016/10/31 15:47:16 -------------------------------------------------------
package main`
`import (
	"log"
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api"
)
`
`func main() {
	tgbotapi.#
}
2016/10/31 15:47:16 -------------------------------------------------------
2016/10/31 15:47:16 Found "log" at "/usr/local/Cellar/go/1.7.3/libexec/pkg/darwin_amd64/log.a"
2016/10/31 15:47:16 Import path "github.com/go-telegram-bot-api/telegram-bot-api" was not resolved
2016/10/31 15:47:16 Gocode's build context is:
2016/10/31 15:47:16  GOROOT: /usr/local/Cellar/go/1.7.3/libexec
2016/10/31 15:47:16  GOPATH: /Users/spalf/dev/golang/Users/spalf/dev/golang
2016/10/31 15:47:16  GOOS: darwin
2016/10/31 15:47:16  GOARCH: amd64
2016/10/31 15:47:16  BzlProjectRoot: ""
2016/10/31 15:47:16  GBProjectRoot: ""
2016/10/31 15:47:16  lib-path: "/Users/spalf/dev/golang/pkg/"
2016/10/31 15:47:16 Error parsing input file (inner block):
2016/10/31 15:47:16  8:11: expected selector or type assertion, found ';'
2016/10/31 15:47:16 extracted expression tokens: tgbotapi
2016/10/31 15:47:16 Offset: 0
2016/10/31 15:47:16 Number of candidates found: 0
2016/10/31 15:47:16 Candidates are:
2016/10/31 15:47:16 =======================================================`

But:
`$ ls -l /Users/spalf/dev/golang/pkg/darwin_amd64/github.com/go-telegram-bot-api/
total 872
-rw-r--r--  1 spalf  staff  444894 Oct 31 15:24 telegram-bot-api.a`

`$ go env
GOARCH="amd64"
GOBIN="/Users/spalf/dev/golang/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/spalf/dev/golang"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xx/xkz18gqx0qd4r4d2ygrcjxc80000gn/T/go-build127299729=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
`

**Comment by nsf** [comment]
`gocode set lib-path ""`

**Comment by Spalf** [comment]
2016/10/31 16:19:05 Go project path: .
2016/10/31 16:19:05 Got autocompletion request for '/Users/spalf/dev/golang/src/github.com/Spalf/pomodoroBot/main.go'
2016/10/31 16:19:05 Cursor at: 193
2016/10/31 16:19:05 -------------------------------------------------------
package main

import (
	"flag"
	"log"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api"
)

func main() {
...
}
2016/10/31 16:19:05 -------------------------------------------------------
2016/10/31 16:19:05 Found "flag" at "/usr/local/Cellar/go/1.7.3/libexec/pkg/darwin_amd64/flag.a"
2016/10/31 16:19:05 Found "log" at "/usr/local/Cellar/go/1.7.3/libexec/pkg/darwin_amd64/log.a"
2016/10/31 16:19:05 Import path "github.com/go-telegram-bot-api/telegram-bot-api" was not resolved
2016/10/31 16:19:05 Gocode's build context is:
2016/10/31 16:19:05  GOROOT: /usr/local/Cellar/go/1.7.3/libexec
2016/10/31 16:19:05  GOPATH: /Users/spalf/dev/golang/Users/spalf/dev/golang
2016/10/31 16:19:05  GOOS: darwin
2016/10/31 16:19:05  GOARCH: amd64
2016/10/31 16:19:05  BzlProjectRoot: ""
2016/10/31 16:19:05  GBProjectRoot: ""
2016/10/31 16:19:05  lib-path: ""
2016/10/31 16:19:05 Error parsing input file (inner block):
2016/10/31 16:19:05  8:11: expected selector or type assertion, found ';'
2016/10/31 16:19:05  10:2: expected ';', found 'IDENT' bot
2016/10/31 16:19:05 extracted expression tokens: tgbotapi
2016/10/31 16:19:05 Offset: 0
2016/10/31 16:19:05 Number of candidates found: 0
2016/10/31 16:19:05 Candidates are:
2016/10/31 16:19:05 =======================================================

**Comment by nsf** [comment]
Well, gocode reports whatever GOPATH is passed in by the gocode client. Fix your editor's environment and it'll work.

**Comment by Spalf** [comment]
Ok, it is textmate issue.
Thanks for help.
