### ISSUE TITLE
panic: unknown export format version 3

### ISSUE THREAD

**Issue by reusee** [nsf/gocode#401]
Auto completion is broken on 1.8 tip.

**Comment by zchee** [comment]
@reusee I was fixed this problem on https://github.com/nsf/gocode/commit/82514c86ff1b37eb29aa979fe51238846857935d

Try updating gocode:

```sh
gocode close && go get -u github.com/nsf/gocode
```

**Comment by mattn** [comment]
@nsf @zchee Is it possible to recognize why completion fail? If it's possible to recognize version mismatch, I'll suggest to add new exit code or something to recognize version mismatch. Plugin authors can handle this to users to upgrade gocode.

**Comment by zchee** [comment]
@mattn Yeah, `unknown export format version N` error message are not user-friendly.
This error message is originally from the `gcimporter15`, mostly for the compiler(or parser) internal.
So It's difficult for users to recognize the mismatch of version.
I was directly carried `gcimporter15` code, Sorry.

But I don't know what behavior(or message) is good, I will follow @nsf opinion for its behavior.

**Comment by nsf** [comment]
The problem is that gocode doesn't have any error reporting in its interface. I guess it will be added one day. For now all I think can be done is to log more about it. Maybe even add explicit suggestion to update gocode. Won't work for all users, but will do for those who use `gocode -s -debug`.

**Comment by mattn** [comment]
I think this is useful to avoid you to be filed issue like this. So it should be programmable.
