### ISSUE TITLE
company-go , broken auto-completion

### ISSUE THREAD

**Issue by dineshbhosale** [nsf/gocode#404]
`gocode` uses the output from `go install` to provide its suggestions.

If you use emacs alone for writing Go code, everything is fine, but if you also use Sublime Text (with Go plugins), then Sublime Text updates (via `go install`) Go packages that emacs depends on and that somehow prevents emacs company-go from giving correct suggestions because of incorrect suggestions provided by `go install` done by sublime text.

`Company-go` should provide an option to run `go install` on every file save to ensure that correct and up to date suggestions are given.

**Comment by nsf** [comment]
I do not understand what you mean.

**Comment by dineshbhosale** [comment]
company-go, Go-sublime and autocomplete-go uses gocode and packages are installed in same location and are shared between sublime text, spacemacs and atom as well ,

So when you start editing same file using atom and sublime-text, they run `go install` in background to make sure that correct auto-completion suggestions are given.

But, company-go does not provide any option or functionality to run `go install` to make sure that correct suggestions are given. As a result, company-go is returning incorrect and not up-to-date suggestions.

[See FAQ of autcomplete-go](https://github.com/joefitzgerald/autocomplete-go#faq)

**Comment by nsf** [comment]
Well, my stance on this is pretty simple - it's not my job to run `go install` as far as plugins shipped with gocode are concerned. If I were an evil dictator here I would definitely remove the `autobuild` feature as well. Never understood the kind of workflow when people work on two packages simultaneously without compiling one before moving to the next one. Maybe it's a habit people have coming from dynamic languages background (python, ruby, etc.), where you just edit stuff without compiling.

And I often disagree how people do their Go plugins, you mentioned sublime-text, but I had to write a minimal plugin for sublime myself to make it work the way I like. It definitely doesn't run anything, except gofmt.

So, there is a short answer to that and it is simple: I don't want to implement anything like that in any of the plugins in the repository.

The long answer is that this can be considered as a flaw in gocode's architecture. Gocode should really parse source files and resolve type info using source files alone and fallback to binaries only if there are no source files. But it would be somewhat a major rewrite and with its own set of issues. Right now I don't have much desire and time to work on that. The long answer means the problem will go away eventually (and eventually means it may as well take several years) and no editor will have to run `go install`.

**Comment by dineshbhosale** [comment]
For example if installed `*.a` files from `$GOPATH/pkg/` somehow got deleted then and auto-completion in emacs for external go packages will completely stop working, to prevent this, we need to run `go install` ,  [autcomplete-go](https://github.com/DisposaBoy/GoSublime)  and [gosublime](https://github.com/DisposaBoy/GoSublime) plugin are providing this as default functionality, as soon as you open a file in sublime text, it automatically installs related packages to make sure that up-do-date suggestions are given. 

I have temporarily fixed this issue by adding go install in my task runner. Maybe someone will create a separate plugin for emacs to fix this issue.
