### ISSUE TITLE
Can't autocomplete struct inside a package

### ISSUE THREAD

**Issue by zhexuany** [nsf/gocode#407]
Check the screenshot for more information. 

![screen shot 2016-12-06 at 16 20 46](https://cloud.githubusercontent.com/assets/13320708/20918033/f87d20e6-bbcf-11e6-9f1d-a5404ddbccbf.png)

**Comment by zhexuany** [comment]
It was me being stupid. I forgot to import the package. But this leads to a question:

whether `gocode` support auto import package?

**Comment by nsf** [comment]
It does, but only for direct autocompletions of the built-in packages. E.g. if you write "flag." it will autoimport it, otherwise it won't.

**Comment by nsf** [comment]
Oh and you need to set `gocode set unimported-packages true`.

**Comment by zhexuany** [comment]
I set `unimported-packages` as `true`. But I still can't autoimport it. Any idea about this?

**Comment by nsf** [comment]
I hope you read what I said, it only works on direct autocompletions, e.g.:

![example](https://cloud.githubusercontent.com/assets/12567/20920591/6c64a17c-bbc2-11e6-9eec-245db961c2f0.png)

**Comment by zhexuany** [comment]
That is all misunderstanding. I thought autoimport actually mean write package into `import ()`.  
For example, if we have import looks like
~~~
import (
           "os"
)
~~~

After, we write `flag` in other method, the import body will become 

~~~
import (
            "os"
            "flag"
)
~~~

This is what I want to. In addition, without actually import `flag`, further autocompletion will not work. The screenshot demonstrate this.

**Comment by nsf** [comment]
Yeah, there is a tool called goimports or something like that, which does it. In gocode I can't really enforce things like that, because gocode is only an autocompletion provider. All the actual job is done by many editor plugins and to enforce a feature like that I will have to push it into all those plugins out there. So all I could do (and it was requested) is what I did.

**Comment by zhexuany** [comment]
Oh, really? I did not know that. Thanks for your kindly help. :=)
