### ISSUE TITLE
panic: unknown export format version -1 ("v0")

### ISSUE THREAD

**Issue by mattn** [nsf/gocode#408]
![](http://go-gyazo.appspot.com/e065d41c1cd87b14.png)

```
go version devel +94a4485 Tue Dec 6 22:33:48 2016 +0000 windows/amd64
```

**Comment by zchee** [comment]
@mattn I'm interested why the error occurs because I contributed some things related to bimport. (I want to take responsibility for what I do)
Would you mind explaining the situation where the error occurred?

**Comment by mattn** [comment]
>Would you mind explaining the situation where the error occurred?

In the stacktrace. And I did completion with below's code.

```
package

import (
    "fmt"
)

func main() {
    fmt.
}

**Comment by zchee** [comment]
@mattn Hmm, that's strange because I also using go devel, now `+61db2e4efa`. and it's fine.
I'll investigate the situation where the export format will `-1` (actually, `p.version == -1, versionstr == v0`)
Thanks for information.

**Comment by mattn** [comment]
Sorry delay. I don't make sure but this seems to be solved in tip.

**Comment by ekle** [comment]
still having this problem with 5070dacabf2a80deeaf4ddb0be3761d06fce7be5

**Comment by zchee** [comment]
@ekle What is situation? same as example code posted by mattn?

If you tell me you using go version, I can test it as same situation and environment.

Also, I don't know whether the related things, but it is worth of
- `go get -u -v github.com/nsf/gocode`
- `go install -a -v std`

**Comment by ekle** [comment]
tried your commands, they do not help
also tried it with `go version go1.7.4 linux/amd64`
i tried the example above and i don't get an error there

`panic: unknown export format version -1 ("v0")
1(runtime.call32): /usr/local/go/src/runtime/asm_amd64.s:479
2(runtime.gopanic): /usr/local/go/src/runtime/panic.go:458
3(main.(*gc_bin_parser).parse_export): .../go/src/github.com/nsf/gocode/package_bin.go:131
4(main.(*package_file_cache).process_package_data): .../go/src/github.com/nsf/gocode/package.go:141
5(main.(*package_file_cache).update_cache): .../go/src/github.com/nsf/gocode/package.go:90
6(main.update_packages.func1): .../go/src/github.com/nsf/gocode/autocompletecontext.go:381
7(runtime.goexit): /usr/local/go/src/runtime/asm_amd64.s:2086

panic: One of the package cache updaters panicked
1(runtime.call32): /usr/local/go/src/runtime/asm_amd64.s:479
2(runtime.gopanic): /usr/local/go/src/runtime/panic.go:458
3(main.update_packages): .../go/src/github.com/nsf/gocode/autocompletecontext.go:389
4(main.(*auto_complete_context).update_caches): .../go/src/github.com/nsf/gocode/autocompletecontext.go:165
5(main.(*auto_complete_context).apropos): .../go/src/github.com/nsf/gocode/autocompletecontext.go:303
6(main.server_auto_complete): .../go/src/github.com/nsf/gocode/server.go:196
7(main.(*RPC).RPC_auto_complete): .../go/src/github.com/nsf/gocode/rpc.go:26
8(runtime.call64): /usr/local/go/src/runtime/asm_amd64.s:480
9(reflect.Value.call): /usr/local/go/src/reflect/value.go:434
10(reflect.Value.Call): /usr/local/go/src/reflect/value.go:302
11(net/rpc.(*service).call): /usr/local/go/src/net/rpc/server.go:383
12(runtime.goexit): /usr/local/go/src/runtime/asm_amd64.s:2086
`

**Comment by zchee** [comment]
@ekle Hm.
I don't know what you edited `.go` code(if no problem, could you post to such as gist?), but it seems to `import`-ed some non-stdlib packages.
such as
- `github.com/coreos/etcd/clientv3.a`
- `golang.org/x/net/context.a`

It’s unlikely, and it may not be possible as an internal implementation of gocode(because have `package_text.go` parser), but if installed these packages long ago, it may be different from the go object binary spec of `go1.7.4`.
IIRC Go's binary spec officially changed at 1.7(maybe), so means like:
- go runtime: 1.7.4
- github.com/coreos/etcd/clientv3.a: installed using go1.6
- golang.org/x/net/context.a: installed using go1.6

So, it is worth of re-install(go get) these packages using `go1.7.4`.

If you still have same errors, need to do more detailed debugging. or, @nsf may identify the problem.

**Comment by ekle** [comment]
ok, i deleted ../go/pkg/linux_amd64 completely and it helped.
go get -a -u -v
go build -a
did not help.
maybe this has to do with vendoring.

**Comment by zchee** [comment]
@ekle Ah, yeah if you use vendor directory, go toolchain will create .a object file to same directory path on $GOPATH/pkg.
But solved problem? I'm glad hear that.

I think you already know, but I'll leave comment for other users.

`$GOPATH/src/github.com/zchee/foo/vendor/github.com/zchee/bar`

If build foo package, That vendored `bar` packages object file will create at

1.
```sh
$GOPATH/pkg/linux_amd64/github.com/zchee/foo/vendor/github.com/zchee/bar.a
```

So yes, `go get -u github.com/zchee/bar` is did not helped.
Update only

2.
```sh
$GOPATH/pkg/linux_amd64/github.com/zchee/bar.a
```

but gocode will parses `1` object file. if that binary spec is old, gocode will PANIC.

---

Now I write above comment based on my (brain) memory. It may be wrong.
