### ISSUE TITLE
gocode does not work with emacsclient

### ISSUE THREAD

**Issue by zhexuany** [nsf/gocode#409]
gocode works prefect fine with emacs. But when I launched emacs in daemon, and run emacsclient. gocode seems does not work. Is there anyone can tell me how to fix this? The built in lib works just fine such as `fmt` or `flag`.  For all other lib such as any project I imported from github.com does not work at all.

**Comment by nsf** [comment]
Take a look at emacs daemon env vars, perhaps GOPATH is wrong.

**Comment by zhexuany** [comment]
I checked. `GOPATH` is correct. That actually makes sense. `gocode` only work for built in lib such as `fmt` or `flag` but not for projects imported from `github.com`.

**Comment by nsf** [comment]
Well, I don't know. Try `gocode close && gocode -s -debug` in a separate terminal window. And then do your autocompletion, gocode prints out all the info about autocompletion request, including env vars and whether it resolved libraries or not. Usually there are some helpful hints in this output. If you don't resolve it yourself, paste it here, I'll take a look.

**Comment by zhexuany** [comment]
I found something suspicious. 

~~~
Import path "github.com/zhexuany/esm-filter/run" was not resolved
~~~

Any idea about this?

**Comment by nsf** [comment]
No, it tells me that the package path was not resolved. But at the beginning of the output it should also dump env vars and such. Paste it all here. You can skip the go file itself it prints out.

**Comment by zhexuany** [comment]
~~~
2016/12/12 16:10:17 -------------------------------------------------------
2016/12/12 16:10:17 Found "flag" at "/usr/local/go/pkg/linux_amd64/flag.a"
2016/12/12 16:10:17 Found "fmt" at "/usr/local/go/pkg/linux_amd64/fmt.a"
2016/12/12 16:10:17 Found "io" at "/usr/local/go/pkg/linux_amd64/io.a"
2016/12/12 16:10:17 Found "log" at "/usr/local/go/pkg/linux_amd64/log.a"
2016/12/12 16:10:17 Found "math/rand" at "/usr/local/go/pkg/linux_amd64/math/rand.a"
2016/12/12 16:10:17 Found "os" at "/usr/local/go/pkg/linux_amd64/os.a"
2016/12/12 16:10:17 Found "os/signal" at "/usr/local/go/pkg/linux_amd64/os/signal.a"
2016/12/12 16:10:17 Found "strings" at "/usr/local/go/pkg/linux_amd64/strings.a"
2016/12/12 16:10:17 Found "syscall" at "/usr/local/go/pkg/linux_amd64/syscall.a"
2016/12/12 16:10:17 Found "time" at "/usr/local/go/pkg/linux_amd64/time.a"
2016/12/12 16:10:17 Import path "github.com/zhexuany/esm-filter/run" was not resolved
2016/12/12 16:10:17 Gocode's build context is:
2016/12/12 16:10:17  GOROOT: /usr/local/go
2016/12/12 16:10:17  GOPATH:
2016/12/12 16:10:17  GOOS: linux
2016/12/12 16:10:17  GOARCH: amd64
2016/12/12 16:10:17  BzlProjectRoot: ""
2016/12/12 16:10:17  GBProjectRoot: ""
2016/12/12 16:10:17  lib-path: ""
2016/12/12 16:10:17 Error parsing input file (inner block):
2016/12/12 16:10:17  10:6: expected selector or type assertion, found ';'
2016/12/12 16:10:17  11:2: expected ';', found 'IDENT' fmt
2016/12/12 16:10:17 extracted expression tokens: run
2016/12/12 16:10:17 Offset: 0
2016/12/12 16:10:17 Number of candidates found: 0
2016/12/12 16:10:17 Candidates are:
2016/12/12 16:10:17 =======================================================
~~~

**Comment by nsf** [comment]
> 2016/12/12 16:10:17  GOPATH:

So, GOPATH is empty as I thought. Recheck the GOPATH env var. It should be available to the emacs daemon, not the client. At least I think so, whoever invokes gocode client.

**Comment by zhexuany** [comment]
![image](https://cloud.githubusercontent.com/assets/13320708/21106423/05166ddc-c0c9-11e6-9f88-d261de00b041.png)
Above picture is the result when I executed `echo $GOPATH`.

**Comment by nsf** [comment]
Is that from `M-x getenv <enter> GOPATH <enter>`? In any case, I'm not that familiar with emacs client/server thing. All I can see on the gocode side is that it doesn't get the right env var. I can't fix it.

**Comment by zhexuany** [comment]
no. When I tried to execute the command you just gave me. `emacsclient` does not have an entry called `GOPATH`.  So the question is actually become how can I make `GOPATH` being visible to `emacsclient`?

**Comment by nsf** [comment]
That's a good question, but I have no idea.

**Comment by zhexuany** [comment]
I just create a new issue in `spacemacs`. I hope someone can help me out. Additionally, this is related with `gocde`, it will be nice if I reference it back. 

https://github.com/syl20bnr/spacemacs/issues/7950
