### ISSUE TITLE
Panic when updating to 1.8

### ISSUE THREAD

**Issue by ammario** [nsf/gocode#410]
Hi, I get the following panic when attempting autocomplete seemingly anywhere. I'm using vscode-go

```
panic: invalid encoding format in export data: got 'v'; want 'c' or 'd'
1(runtime.call32): /usr/local/go/src/runtime/asm_amd64.s:501
2(runtime.gopanic): /usr/local/go/src/runtime/panic.go:489
3(main.(*gc_bin_parser).parse_export): /home/ammar/Projects/gopath/src/github.com/nsf/gocode/package_bin.go:93
4(main.(*package_file_cache).process_package_data): /home/ammar/Projects/gopath/src/github.com/nsf/gocode/package.go:141
5(main.(*package_file_cache).update_cache): /home/ammar/Projects/gopath/src/github.com/nsf/gocode/package.go:90
6(main.update_packages.func1): /home/ammar/Projects/gopath/src/github.com/nsf/gocode/autocompletecontext.go:370
7(runtime.goexit): /usr/local/go/src/runtime/asm_amd64.s:2184
```

**Comment by nsf** [comment]
Thanks for letting me know, but Go 1.8 is not released yet. I don't do fixes until right before the release. AFAIK 1.8 is scheduled for the end of January next year.

If somebody else provides a patch to accommodate changes in the package format that'd be great.

**Comment by zchee** [comment]
@ammario It seems to not a bug, maybe your gocode is old binary.

```sh
panic: invalid encoding format in export data: got 'v'; want 'c' or 'd'
# and
3(main.(*gc_bin_parser).parse_export): /home/ammar/Projects/gopath/src/github.com/nsf/gocode/package_bin.go:93
```

IIRC, that error is below code.
https://github.com/nsf/gocode/blob/f535dc686130fcc7b942c504ce5903222a205ca3/package_bin.go#L93

Could you update `gocode` binary, like `go get -u github.com/nsf/gocode`?

**Comment by nsf** [comment]
Yes, sorry, I've made a misjudgement. What @zchee says seems to be legit.

**Comment by ammario** [comment]
ah, I didn't properly update. I apologize for the preemptive issue. Thanks :)
