### ISSUE TITLE
proposal: add test file using "testing" package

### ISSUE THREAD

**Issue by zchee** [nsf/gocode#418]
Hi,

I'm working on #417 now.
At the moments(just now), there is a problem that completion candidates after alias-ed `struct` child methods candidates are not displayed at all. So need change any internal function (other than `package_bin.go`)
I know gocode have `_testing` test. But it's mock testing. If change any `func` behavior for backporting, It's difficult to test whether it causes bugs.
And, I do not understand all the internal implementation, like you. So it is necessary to test run the actual completion candidate.
So, I want to add the function level testing that using `testing` stdlib package in the future. But yes, I also know gocode now "maintenance mode". This proposal **not good, not sense**.
Also, If adding test file, it needs to introduce the CI test that I proposed earlier. but it was rejected.

However, you said that you guarantee the operation of gocode against stable Go1 version. I also decided to correspond to the `tip` as much as possible. (Yeah, I'm not an owner of gocode. without consent. But I'm glad if that helped you as a result)
I think that it will be nice if it helps new Go runtime feature backporting etc. And, If you're not planned to support Go 2.0, I will write a new completion engine. Maybe also it will be helpful.

Anyway, I {want to | will write} a function level testing. The subject of this issue is whether I can pull request it.
If not like, I'll maintenance it in the forked my repository (only test file). it's no problem because this test is almost for me (but it might be helpful for other contributors).
What do you think about it?

**Comment by nsf** [comment]
Add everything you need. All that matters is that feature is working. When it's working we'll see what and how we can merge.

**Comment by zchee** [comment]
@nsf Thanks.
I'll only include the mock test in that PR because it is the priority to fully works for type alias. But I'll add some test in the future.

Is CI ok too? If so, as for CI, I don't have commit privilege of the gocode repository, so need to your setup it. I will mention to you when sent PR that adding configuration(like `.travis.yml` or `circle.yml`) file.
Well... the CI test is not useful without commit privileges(authority of managing the CI) like can't sent rebuild request, can't notification settings. so maybe I'll only adapt to my forked repository.

**Comment by nsf** [comment]
I don't think gocode needs CI. CI is useful for large scale projects with a fast update rate and frequent deployments. Gocode isn't one of them.

**Comment by zchee** [comment]
@nsf Ah, I thought not CI for testing. actually, that's useful for test coverage.
i.e, if use codecov.io, I(we) can easily see the coverage.

https://codecov.io/gh/zchee/appleopensource/src/bdba210c3dbaee1b140c5d10680a2f64fe472a28/appleopensource.go

With chrome extension:

![screen shot 2017-02-09 at 4 06 09](https://cloud.githubusercontent.com/assets/6366270/22752784/23343bd2-ee7d-11e6-8fde-5d7f269acbba.png)

So, I want to CI test. but it's can see on zchee/gocode, so maybe CI setting are I'll only adapt to my forked repository.

**Comment by nsf** [comment]
You can get coverage via `go tool cover` as well. I do agree with you that it'd be nice to convert tests to `go test` format instead of using external scripts.

**Comment by zchee** [comment]
@nsf OK, got it and agreed :)
Anyway, I'll continue to try write test and support type alias.

I close this issue when I pull request the adding first test file.
