### ISSUE TITLE
IntelliSense doesn't understand abbreviated elements when initializing an array/slice of structs

### ISSUE THREAD

**Issue by ramya-rao-a** [nsf/gocode#422]
_From @thrnio on February 10, 2017 1:49_

Consider the following code:

~~~go
package controller

type foo struct {
	bar string
	baz bool
}

var foobar = []foo{
	{bar: "bar", baz: true},
}
~~~

This is valid Go code, since it's optional to specify `foo` before each individual element (i.e., `{bar: "bar", baz: true}`). IntelliSense, however seems to attempt to autocomplete as if it were just `foo{ | }`, not `[]foo{ | }`. Explicitly doing 

~~~go
[]foo{
    foo{bar: "bar", baz: true},
}
~~~

works better.

![golang-array-struct-intellisense-bug](https://cloud.githubusercontent.com/assets/97464/22809008/30560036-eee4-11e6-823b-8c843aaca631.png)

(Ignore the invalid use of `:=`; I was quickly throwing something together enough to get a screenshot and wasn't paying attention. It doesn't change the behavior from the code snippet above.)

_Copied from original issue: Microsoft/vscode-go#783_

**Comment by ramya-rao-a** [comment]
@thrnio We use `gocode` for the completions, where we pass the cursor position and the file contents and show what is returned by `gocode`. Therefore, will move this issue to the repo for `gocode`

**Comment by nsf** [comment]
Yes, it's a known issue, I'll see if it can be easily fixed. But don't expect the patch until the weekend. Struct field autocompletion is far from perfect in general. Sometimes it gets triggered when you're at the beginning of the function and it picks up the return type as a struct type. That's something to look at as well.

**Comment by nsf** [comment]
I've added a hack which seems to be handling this case. But keep in mind that this is a hack. Gocode's context deduction isn't too fancy, all it does is that it looks at lexical elements of the source code before the cursor and tries to figure out what it is. So this hack works only for the first element of an array. Which is better than nothing. But I'll keep the issue open if somebody wants to try to improve it. The code to look at is: https://github.com/nsf/gocode/blob/master/cursorcontext.go#L119-L155

To be clear, what I've added makes this work:

![case](https://cloud.githubusercontent.com/assets/12567/23101627/b1bbd326-f6b9-11e6-8e9e-0e6c032cda8e.png)

But this doesn't work:

![case2](https://cloud.githubusercontent.com/assets/12567/23101632/d6ece888-f6b9-11e6-837e-ad8cee642cbf.png)

**Comment by nsf** [comment]
![fix](https://cloud.githubusercontent.com/assets/12567/23339409/96d8b530-fc43-11e6-99d1-b6bf66031391.png)

Works now even for case that I mentioned it didn't. Will close the issue for now, if you have anything to add or complain about, feel free to reopen it.

**Comment by ramya-rao-a** [comment]
Thanks @nsf! I can confirm this is working now.

@thrnio Update your `gocode` 
- `gocode close`
- `go get -u github.com/nsf/gocode`
And you should be able to see the fix as well.
