### ISSUE TITLE
Gocode panics when using golang 1.8

### ISSUE THREAD

**Issue by zolamk** [nsf/gocode#423]
Gocode doesn't display auto complete information, instead it displays ´PANIC PANIC PANIC´

**Comment by nsf** [comment]
Tried `gocode close && gocode get -u github.com/nsf/gocode`?

**Comment by sheepbao** [comment]
@nsf  `gecode close && go get -u github.com/nsf/gocode` is work.

**Comment by TatriX** [comment]
As both comments have typos, here is a ready for copy-paste working solution:
```
gocode close && go get -u github.com/nsf/gocode
```

**Comment by nsf** [comment]
Sorry about the typo, fixed mine.

**Comment by zolamk** [comment]
´gocode close && go get -u github.com/nsf/gocode´ fixed it...thanks all.
