### ISSUE TITLE
Panics with deoplete-go on Windows

### ISSUE THREAD

**Issue by xelra** [nsf/gocode#424]
I'm trying to use deoplete-go in Windows in Neovim, which builds on top of gocode.

Unfortunately I get `[deoplete] gocode panicked` errors. I'm still seeing completions though.

Here is the output of `gocode -s -debug` for one such error:
```
2017/02/18 01:26:13 Go project path: hello
2017/02/18 01:26:13 Got autocompletion request for 'C:\Users\xelra\go\src\hello\hello.go'
2017/02/18 01:26:13 Cursor at: 83
panic: runtime error: slice bounds out of range
1(runtime.call32): C:/Go/src/runtime/asm_amd64.s:514
2(runtime.gopanic): C:/Go/src/runtime/panic.go:489
3(runtime.panicslice): C:/Go/src/runtime/panic.go:35
4(main.server_auto_complete): C:/Users/xelra/go/src/github.com/nsf/gocode/server.go:190
5(main.(*RPC).RPC_auto_complete): C:/Users/xelra/go/src/github.com/nsf/gocode/rpc.go:26
6(runtime.call64): C:/Go/src/runtime/asm_amd64.s:515
7(reflect.Value.call): C:/Go/src/reflect/value.go:434
8(reflect.Value.Call): C:/Go/src/reflect/value.go:302
9(net/rpc.(*service).call): C:/Go/src/net/rpc/server.go:387
10(runtime.goexit): C:/Go/src/runtime/asm_amd64.s:2197
```

This is my `go env`:
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\xelra\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

```

**Comment by zchee** [comment]
@xelra Hi, I'm deoplete-go author, also gocode contributor.
IIRC it seems to deoplete-go bug(maybe) But I don't know what your edited Go sources.
So, Could you re-post to deoplete-go issue with sample Go sources?

Thanks.

**Comment by nsf** [comment]
Seems like plugin passes cursor position outside of boundaries of the currently edited file. A source code example would be nice indeed. I also added some code for debug mode which does the boundaries check for cursor. It would yield a more useful error message. However it won't include the source code still though.

**Comment by zchee** [comment]
@nsf Yeah, maybe I think my plugin was get the wrong buffer or cursor position.
Thanks for adding the useful debug log message :)

**Comment by xelra** [comment]
As requested, I've created a cross-issue on zchee/deoplete-go.

The source code is a simple "hello world" file:
```go
package main

import "fmt"

func main() {
    fmt.Printf("hello, world\n")
}
```

**Comment by zchee** [comment]
@xelra Are you still have this issue? If so, As @nsf said,

> Seems like plugin passes cursor position outside of boundaries of the currently edited file

I think too, because if you tested with posted "hello world" file, that end of byte offset is `75`. So `83` offset is impossible.

```sh
.
.
2017/02/18 01:26:13 Cursor at: 83
.
.
```

I think this issue is not gocode side, maybe Neovim's API(or wrong get offset by the deoplete-go). I'll create Windows10 VM on VMWare and try to test it.
Anyway, It seems better to close this issue.

**Comment by xelra** [comment]
Yes, I'm still having this issue. I just set it up on another Windows 10 Professional machine and it's exactly the same. Latest version of everything: Neovim, Neovim-Qt, gocode, deoplete.nvim and deoplete-go.

**Comment by zchee** [comment]
@xelra I see.
I'm macOS but works fine. So it certainly seems to be only of Windows issue.
If Neovim's API is wrong, another plugin will also have the same issue. I want to try to investigate this issue.

OK, Let's close this issue and move the discussion place there:
https://github.com/zchee/deoplete-go/issues/94

**Comment by Shougo** [comment]
I get the reason.
It seems deoplete-go error.
I will fix it later.
