### ISSUE TITLE
Error building on Ubuntu 16.10

### ISSUE THREAD

**Issue by sambengtson** [nsf/gocode#430]
I'll apologize in advance because I feel that I'm missing something simple.  But having trouble building on Ubuntu 16.10 with go1.8.  Here is the error I'm getting:

```
sam@sam-lappy:~/.gvm/pkgsets/go1.8/global/src$ go get github.com/nsf/gocode
# github.com/nsf/gocode
github.com/nsf/gocode/decl.go:133: t.Specs[0].(*ast.TypeSpec).Assign undefined (type *ast.TypeSpec has no field or method Assign)
github.com/nsf/gocode/package_bin.go:220: unknown field 'Assign' in struct literal of type ast.TypeSpec
sam@sam-lappy:~/.gvm/pkgsets/go1.8/global/src$ echo $GOPATH
/home/sam/.gvm/pkgsets/go1.8/global
sam@sam-lappy:~/.gvm/pkgsets/go1.8/global/src$ echo $GOROOT
/home/sam/.gvm/gos/go1.8
```

Is this a real thing or am I going crazy?

**Comment by sambengtson** [comment]
Gocode was being automatically installed by a Visual Studio Code extension.  Manually installing by specifying the -u flag seemed to work.

**Comment by nsf** [comment]
Yeah, sorry for confusion, I just fixed the bug as soon as I introduced it a few minutes ago.
