### ISSUE TITLE
gocode doesn't build on go 1.9 after commit 31552c20

### ISSUE THREAD

**Issue by siebenmann** [nsf/gocode#434]
Commit 31552c20 updated type_alias_build_hack_18.go to include a tag for go1.8.typealias:

```
// +build !go1.9 !go1.8.typealias
```

Unfortunately this is an OR condition, per `godoc go/build`, not an AND one. So instead of building this file on anything other than go1.9 or go1.8.typealias (which I believe is the intended result), it will build on anything that is not both go1.9 and go1.8.typealias, which is everything (since go1.9 is not go1.8typealias and vice versa). That means on go 1.9 (and probably the go 1.8 typealias branch) an attempt to build gocode gets:

```
/u/cks/go/src/github.com/nsf/gocode/type_alias_build_hack_19.go:9: typeAliasSpec redeclared in this block
        previous declaration at /u/cks/go/src/github.com/nsf/gocode/type_alias_build_hack_18.go:9
/u/cks/go/src/github.com/nsf/gocode/type_alias_build_hack_19.go:17: isAliasTypeSpec redeclared in this block
        previous declaration at /u/cks/go/src/github.com/nsf/gocode/type_alias_build_hack_18.go:16
```

This happens because both files are built here.

The solution is to change the condition to `!go1.9,!go1.8.typealias`; the comma creates the AND condition desired.

**Comment by nsf** [comment]
Blame Go devs for not using a proper boolean expression syntax.
