### ISSUE TITLE
[Emacs24 - Fedora25] show-menu’: (file-error "Searching for program" "No such file or directory" "gocode")

### ISSUE THREAD

**Issue by fluteguitar** [nsf/gocode#436]
![image](https://cloud.githubusercontent.com/assets/10528635/23581041/f4abc88e-0132-11e7-9a7d-dbfe1a70b5f1.png)

**Comment by nsf** [comment]
Can't you read? It's in the title. Your emacs can't find the "gocode". Where do programs look for other programs? In PATH directories. Add your GOPATH/bin to your PATH and you're good to go. Or whenever the gocode binary is. Make sure the right PATH is visible in emacs by doing `M-x getenv <enter> PATH <enter>`

**Comment by fluteguitar** [comment]
Hello,

Sorry for being idiot. I did add Gopath to my PATH already. But still got some error.
`show-menu’: (file-error "Searching for program" "No such file or directory" "gocode")`


**result** of `M-x getenv <enter> PATH <enter>`
![image](https://cloud.githubusercontent.com/assets/10528635/23581341/041eebde-0138-11e7-9363-0e9d3adc9e6d.png)

**result** of `ls` my GOPATH/bin 
![image](https://cloud.githubusercontent.com/assets/10528635/23581347/135e6f98-0138-11e7-9df0-dd61582bdfc8.png)

**Comment by nsf** [comment]
I don't see /home/nerdyhermit/go/bin on that getenv screenshot. That dir should be in PATH that emacs gets.

**Comment by fluteguitar** [comment]
OK I have got it. Thank for your patience.
It is a silly mistake that I held thought the GOPATH I already exported `/usr/local/go/bin' is what I need to do.
