### ISSUE TITLE
No type-specific autocomplete when using relative imports outside $GOPATH

### ISSUE THREAD

**Issue by zerkms** [nsf/gocode#437]
Disclaimer: I don't know whether `gocode` is supposed to work with code outside of `$GOPATH`, if it's not - please just close it.

The code for reproducing the issue is at https://github.com/zerkms/vscode-golang-relative-import repository.

For the `bar` there is no type specific autocomplete, but instead it suggests all available symbols.

Initially reported at: https://github.com/Microsoft/vscode-go/issues/811

**Comment by nsf** [comment]
Gocode works with compiled packages, that is you need to have a "./bar.a" file relative to your source file to make it work. My suggestion is to forget about relative imports as nobody uses them in Go. There are alternative build systems which allow you to work outside of GOPATH, https://getgb.io/ as an example and gocode supports this particular one.

If however the "go" tool has different behaviour when it comes to relative imports, I didn't know that and then it's a bug.

**Comment by zerkms** [comment]
`go` can `build` and `run` the given code, not sure if it qualifies as the "different behaviour".

I'm not using relative imports (anymore), so it does not affect me personally. So I think you would be the one who makes a decision whether it's a bug :-)

**Comment by nsf** [comment]
`go build` and `go run` are irrelevant because they don't produce .a files. It's a known gocode issue that it requires binary packages and all. One day I'm sure it will work with source files only and this issue will be automatically resolved. But who knows when this "one day" happens. I don't have any practical plans for rewriting it yet.

**Comment by zerkms** [comment]
Yep, I agree. Closing it then. Thanks.
