### ISSUE TITLE
unsafe: non stdlib method

### ISSUE THREAD

**Issue by zchee** [nsf/gocode#440]
Currently `gocode` return the `unsafe` package method is below.

```go
	type @"".Pointer uintptr
	func @"".Offsetof (? any) uintptr
	func @"".Sizeof (? any) uintptr
	func @"".Alignof (? any) uintptr
	func @"".Typeof (i interface { }) interface { }
	func @"".Reflect (i interface { }) (typ interface { }, addr @"".Pointer)
	func @"".Unreflect (typ interface { }, addr @"".Pointer) interface { }
	func @"".New (typ interface { }) @"".Pointer
	func @"".NewArray (typ interface { }, n int) @"".Pointer
```

I do not know the history of the old Go, but now stable Go version provide only of:

```go
	type @"".Pointer uintptr // or ArbitraryType?
	func @"".Offsetof (x ArbitraryType) uintptr
	func @"".Sizeof (x ArbitraryType) uintptr
	func @"".Alignof (x ArbitraryType) uintptr
	// type @"".ArbitraryType int
```

In `type @"".ArbitraryType int`, stdlib unsafe package comment said,
> // ArbitraryType is here for the purposes of documentation only and is not actually
// part of the unsafe package. It represents the type of an arbitrary Go expression.

However, Gogland (Go IDE by JetBrains. That not uses gocode, have self-parser. I do not know the IDE where not used gocode other than this) provides also `ArbitraryType` completion. I don't know which is great.

Anyway, I want to know why APIs that can't be used remain. or are these APIs provides somewhere...?
If so, sorry for annoying.

Thanks.

**Comment by nsf** [comment]
Sorry for not answering quickly. Yeah, I guess I can sync it up. Will remove the extra types. I don't think actually many people use "unsafe", so it shouldn't be a big deal.
