### ISSUE TITLE
remote origin not found

### ISSUE THREAD

**Issue by ml232528** [nsf/gocode#445]
C:\Go\bin\go.exe get -u -v github.com/nsf/gocode
package github.com/nsf/gocode: remote origin not found

**Comment by shurcooL** [comment]
Did you remove the origin remote in the gocode repository?

If you don't have any unsaved work in that repo, the easiest way to fix it would to be remove the repo and `go get -u` it again.

Otherwise, try `git add remote origin https://github.com/nsf/gocode` in the repo.

**Comment by ml232528** [comment]
I Restart the computer， delete the nsf\gocode folder is ok
