### ISSUE TITLE
error while running timer ac-show-menu

### ISSUE THREAD

**Issue by AnirudhVyas** [nsf/gocode#447]
I am trying to switch to emacs off late and in order for me to be productive I need autocomplete for go show up as expected. I get this error - 

Error running timer ‘ac-show-menu’: (file-error "Searching for program" "No such file or directory" "gocode")

While typing code. My (snippet which is of importance pertaining to question I think) init el is - 
```lisp
(add-to-list 'exec-path "/usr/local/bin")
(add-to-list 'load-path "/links/go__path/src/github.com/dougm/goflymake")
(add-to-list 'load-path "/Users/anirudh.vyas/.emacs.d/golisp")
(add-to-list 'load-path "/Users/anirudh.vyas")
(require 'go-mode-autoloads)
(require 'ensime)
(add-hook 'scala-mode-hook 'ensime-scala-mode-hook)
(require 'go-autocomplete)
(require 'auto-complete-config)
(defun auto-complete-for-go ()
  (auto-complete-mode 1))
 (add-hook 'go-mode-hook 'auto-complete-for-go)
(with-eval-after-load 'go-mode
     (require 'go-autocomplete))
```

I am also unable to find auto-complete package on standard emacs MELPA repo. When I tab on auto-complete, I see plethora of auto-complete-* options but never auto-complete alone. Please suggest.

**Comment by nsf** [comment]
I don't use emacs, so can't help you much. But I would suggest using company-mode instead of auto-complete thing.

**Comment by AnirudhVyas** [comment]
ok - well I used company-go el to install emacs package from nsf/gocode but it says package header missing - any ideas there?

**Comment by AnirudhVyas** [comment]
I am going to add a few things and close this ticket, I found out solution to the problem:
[Go Auto Complete setup in emacs on Mac OS X](https://github.com/tleyden/tleyden.github.io/blob/3f14c8dc5b9117240f35dc5cd2c5dcb7592d3e19/source/_posts/2014-05-22-configure-emacs-as-a-go-editor-from-scratch.markdown#autocomplete)

I referred to that and then for me i had to **manually** copy gocode binary to GOPATH/bin to make it work
