### ISSUE TITLE
Add support for export format version 5

### ISSUE THREAD

**Issue by paralin** [nsf/gocode#456]
On Go 1.9:

   panic: unknown export format version 5 ("version 5")

**Comment by paralin** [comment]
Never mind, YouCompleteMe was hiding the fact that an old GoCode was being used...

**Comment by gerrard00** [comment]
Sorry to resurrect a long dead issue, but can you share how you resolved the problem for future we searchers like myself?

**Comment by paralin** [comment]
```
go get -u -v github.com/nsf/gocode
```

**Comment by gerrard00** [comment]
I had tried that but it didn't seem to work. I wound up resolving the issue by going into the YouCompleteMe plugin's copy of gocode (it's a submodule) and updating to the `v.20170907` tag manually. Hacky, but I've got auto-completion again.

**Comment by felixge** [comment]
@gerrard00 thx - that worked for me as well.
