### ISSUE TITLE
Not all tests pass

### ISSUE THREAD

**Issue by mrmagooey** [nsf/gocode#462]
With the repository clean and at commit f1eef9a6ba005abb145d7b58fdd225e83a3c6a05, running `_testing/all.bash` results in three tests failing. 

    <earlier tests truncated>
    test.0053: PASS!
    test.0054: FAIL!
    -----------------------------------------------------------------
    Got:
    Nothing to complete.
    -----------------------------------------------------------------
    Expected:
    Found 4 candidates:
      func Foobarer() string
      var A int
      var B int
      var C float64
    -----------------------------------------------------------------
    test.0055: FAIL!
    -----------------------------------------------------------------
    Got:
    Nothing to complete.
    -----------------------------------------------------------------
    Expected:
    Found 3 candidates:
      var Jim string
      var John string
      var Kim string
    -----------------------------------------------------------------
    test.0056: FAIL!
    -----------------------------------------------------------------
    Got:
    Found 3 candidates:
      var A int
      var B int
      var C int
    -----------------------------------------------------------------
    Expected:
    Found 5 candidates:
      func MethodMe() bool
      func MethodYou() bool
      var A int
      var B int
      var C int
    -----------------------------------------------------------------
    test.0057: PASS!
    test.0058: PASS!
    test.0059: PASS!
    
    Summary (total: 59)
      PASS: 56
      FAIL: 3

System details:

    go version go1.8.3 darwin/amd64 

These failures also occur using `run.py` and `tcl.sh`.

**Comment by nsf** [comment]
That's intentional. They will pass on Go 1.9.
