### ISSUE TITLE
cant get it to work , Windows 10

### ISSUE THREAD

**Issue by slicken** [nsf/gocode#465]
I installed Go 1.83 in c:\go
I installed VS Code
I set my GOPATH to c:\slk\
-------------------------------------------------->>>
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\slk\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
-------------------------------------------------.
I run Command prompt..
cd \slk\
code test.go
install  the Go package
restart VS Code

when i try install gocode I get this message:
-------------------------------------->>
Installing 1 tool
  gocode

Installing github.com/nsf/gocode FAILED

1 tools failed to install.

gocode:
Error: Command failed: C:\Go\bin\go.exe get -u -v github.com/nsf/gocode
github.com/nsf/gocode (download)
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/nsf/gocode: exec: "git": executable file not found in %PATH%
github.com/nsf/gocode (download)
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/nsf/gocode: exec: "git": executable file not found in %PATH%
----------------------------------------------------------------------------------------------.

whats wrong?
I have tryed install and reinstall still dont work.

**Comment by nsf** [comment]
It's written right there in your error message, even with a link.
> Error: Command failed: C:\Go\bin\go.exe get -u -v github.com/nsf/gocode
> github.com/nsf/gocode (download)
> go: missing Git command. See https://golang.org/s/gogetcmd

**Comment by slicken** [comment]
Sorry, thout I installed it, there is still Issues:

F12 **Go to definition** dont shows anything.

And i get this error message under the Git tab

> Using git 2.14.1.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> fatal: Not a git repository (or any of the parent directories): .git
>

**Comment by nsf** [comment]
Gocode doesn't provide "Go to definition" functionality. So, not sure what it takes to make this work on vscode. I know some people work on a proper Go langauge service thing, which probably will support that kind of functionality. But I'm not sure about the state of that project and don't even recall its name. Can't help you with that.

**Comment by dominikh** [comment]
- Go to definition, in vscode, is provided by godef or the optional language server
- There are two language server projects for Go: go-langserver by Sourcegraph, and my (not yet released) replacement for the same.

**Comment by slicken** [comment]
The gocode is working perfekt, I had to mute three returns in three diffrent go files with ' // ' to get it work. But after I did it works like a charm.

Thank you for you help!
My Go definition issue is OT so ill close this thread.
