### ISSUE TITLE
company-go Company: backend company-go error "Wrong type argument: stringp, nil" with args (candidates )

### ISSUE THREAD

**Issue by Xanderio** [nsf/gocode#466]
emacs version: GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.16) of 2017-07-16
company version: 0.9.4

**Comment by kosh04** [comment]
I also got the same problem.

Try update gocode command (`go get -u github.com/nsf/gocode`)

**Comment by Xanderio** [comment]
That fixed the issue

**Comment by mhusmann** [comment]
Thanks kosh04. I updated gocode now everything works fine again

**Comment by l9f** [comment]
So what to do if getting this same error and gocode updated?

**Comment by chunzhouyu** [comment]
i meet this error also, as @kosh04  said, update gocode is not suit me.
my emacs version is GNU Emacs 26.1
go version go1.10.3 darwin/amd64

**Comment by albttx** [comment]
Updated gocode did not fix the issue, i'm with the same version as @chunzhouyu (exept go 1.11)

**Comment by kostspielig** [comment]
This [comment](https://github.com/nsf/gocode/issues/477#issuecomment-333338950) from the other thread did the trick for me:

After updating gocode, don't forget to kill the server which might be running: `gocode close`. New one will start automatically. Also make sure there is only one gocode binary on your PATH: `which -a gocode`.
