### ISSUE TITLE
Incorrect parsing of parametric function Result

### ISSUE THREAD

**Issue by guns** [nsf/gocode#469]
According to https://golang.org/ref/spec#Function_types, a function can declare its return types as a [list of parameters](https://golang.org/ref/spec#Parameters). The following function, therefore, is valid:

```go
func f() (a, b io.Reader, c error) {
	return
}
```

Gocode, however, incorrectly determines that the second return type from `f` is `error`, not `io.Reader`, as demonstrated by the following:

```go
package main

func f() (a, b io.Reader, c error) { return }

func main() {
	a, b, c := f()
	b.
}
```

With the above saved as `issue.go`:

```
$ gocode -in ./issue.go autocomplete 94
Found 1 candidates:
  func Error() string
```

Thank you for `gocode`!

**Comment by nsf** [comment]
Thanks for reporting it.
