### ISSUE TITLE
Tag a new release for gocode

### ISSUE THREAD

**Issue by jacksgt** [nsf/gocode#470]
Hi @nsf,

could you please tag a new release for gocode?
This will update the Emacs package go-autocomplete mode on [MELPA stable](https://stable.melpa.org/#/go-autocomplete) (which is quite out of date now, release 20150303).

Thanks!

**Comment by nsf** [comment]
Added tag: https://github.com/nsf/gocode/tree/v.20170907

**Comment by jacksgt** [comment]
Great, thank you!

(The Emacs [go-autocomplete package on MELPA stable(https://stable.melpa.org/#/go-autocomplete)] is now at 20170907
