### ISSUE TITLE
Impolite and resource intensive

### ISSUE THREAD

**Issue by Davejkane** [nsf/gocode#478]
Whenever I change branch on a large project I can see at least 50 processes called gocode and then the same number of processes called compile. I can't really investigate further though because at 100% CPU, my computer is completely crippled. I have to cold kill and restart. Why does go code need 100% CPU?

**Comment by nsf** [comment]
You're using an experimental feature called "autobuild". Disable it with `gocode set autobuild false`. Some editors may set this option for you, if so, switch to a different editor or an editor plugin.

**Comment by nsf** [comment]
That's a best guess though. Hard to tell what's going on from your description.
