### ISSUE TITLE
How does the autocompletion work in Vim?

### ISSUE THREAD

**Issue by Integralist** [nsf/gocode#481]
Hi,

I've followed the installation instructions, here is my .vimrc configuration:

```viml
Plug 'nsf/gocode', { 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }
```

But if I try typing I don't get any auto-complete suggestions?

I'm using the latest Go version in Homebrew and I've recently run `:GoInstallBinaries` (via vim-go) so I should be up to date with the relevant tools.

> Note: I do have another auto-complete plugin ('maxboisvert/vim-simple-complete') which I don't know if that affects anything.

Any help appreciated.

Thanks.

**Comment by nsf** [comment]
Sadly I've never used those vim plugin managers. Maybe someone else will help you. Also try googling, I'm sure there are plenty of Go + vim guides. And vim-go is not maintained by me. Gocode has its own plugin which I wrote initially as a reference, but I'm sure vim-go offers more features if that's what you're looking for.

**Comment by cznic** [comment]
I'm using a different setup, but I think invoking the autocompletion is the same: in insertion mode type `<ctrl>-x<ctrl>-o`.

**Comment by Integralist** [comment]
That did it `<ctrl>-x<ctrl>-o` (+ I had to uninstall my other auto-complete plugin as I think it was overriding behavior)

**Comment by cznic** [comment]
FTR: I think https://github.com/fatih/vim-go properly handles the Go-specific autocompletion hook only in .go buffers.
