### ISSUE TITLE
Case-insensitive completion-suggestions?

### ISSUE THREAD

**Issue by metaleap** [nsf/gocode#487]
This bugs me surprisingly often, when completion opens a-few-characters-in then it only offers case-sensitive suggestions, but more often than not I'd like to see all cases as when speedily-typing I don't want to bother with the `Shift` key. 😀 For example, I have a `t` somewhere and on-dropdown only see say `true` and `t` (some local var), but wanted `ToolBeanFactoryProviderInterfaceInjector` (just kidding).

If there isn't a `gocode set` for this (my fairly recent version doesn't show any), I'd be comfortable preparing a PR for this minor thing --- but let me know if you'd be interested (or any other users happening upon this issue/question/thread)?

**Comment by nsf** [comment]
Gocode does case sensitive match first and if there are no results it tries case insensitive match. In addition to that editors may do their own filtering, I guess I could add an option to disable partial filtering on the gocode side. Will try to add it sometime today.

**Comment by nsf** [comment]
Okay, I've added two new options to gocode: "partials" and "ignore-case".

First one will force gocode to return **all** autocompletion results disregarding of a prefix behind the cursor, second one will simply ignore the case when doing prefix matching. Note that editors also perform filtering on their own. Whether editor will behave properly or not is something to find out. Try them both, maybe one or the other will work for you.

**Comment by metaleap** [comment]
Nice!! The `ignore-case` was just what I had in mind, works just fine. What a way to end the year, happy-nu-one :grin:

> Note that editors also perform filtering on their own.

Am aware, hacking on my vsc-plugin-to-become-generalized-multi-editor+multi-language-backend-engine-thingy-one-day  here ;)

**Comment by nsf** [comment]
Oh, yes, I should add to the above that setting first option to **false** will do what I described. It's **true** by default. Probably I could make an inverted one, like "all-results" or something. I don't know. I'm bad at naming.
