### ISSUE TITLE
Autocomplete showing full symbol path

### ISSUE THREAD

**Issue by ns-cweber** [nsf/gocode#501]
I imagine I'm doing something wrong, but I keep seeing the full autocomplete filepath in the autocomplete. This makes the output very hard to visually parse. I tried running with `GOPATH` explicitly set, but it made no difference. Is there a way to truncate to only the package name?

```go
func FromSelect(from !/Users/cweber/Projects/pkg/darwin_amd64/github.com/Masterminds/squirrel.a!squirrel.SelectBuilder, alias string) !/Users/cweber/Projects/pkg/darwin_amd64/github.com/Masterminds/squirrel.a!squirrel.SelectBuilder
```

**Comment by nsf** [comment]
Gocode does that if you run it in debug mode with "-debug" flag. That's normal for that mode.

**Comment by ns-cweber** [comment]
I don't think I am running it in debug mode; here's the invocation:

```
/Users/cweber/Projects/bin/gocode -s -sock unix -addr 127.0.0.1:37373
```

I just installed it with `vim-go`.

**Comment by nsf** [comment]
I think you can also set debug mode implicitly using some of the config options. What `gocode set` returns? E.g.

```
nsf@crey ~/w/s/g/n/gocode> gocode set
propose-builtins false
lib-path ""
custom-pkg-prefix ""
custom-vendor-dir ""
autobuild false
force-debug-output ""
package-lookup-mode "gb"
close-timeout 1800
unimported-packages false
partials true
ignore-case false
class-filtering true
```

Look at "force-debug-output" option. If it's not empty then debug mode will be forced on. Disable it with `gocode set force-debug-output ""`

**Comment by ns-cweber** [comment]
Ah, that was it! Thanks so much!
