### ISSUE TITLE
no completions for anything from github.com/aws/aws-sdk-go-v2 package

### ISSUE THREAD

**Issue by dtenenba** [nsf/gocode#504]
I originally filed https://github.com/joefitzgerald/go-plus/issues/760 but I am wondering if the issue actually belongs here. Details at that link, but basically there is no autocompletion for any objects returned by functions in the `github.com/aws/aws-sdk-go-v2` package. Autocompletion works fine otherwise.

**Comment by nsf** [comment]
Seems like a bug, I'll have a look at it closely tomorrow.

**Comment by nsf** [comment]
Ah, sorry. It's working as intended. I took a look at your example. See Config type here:
https://github.com/aws/aws-sdk-go-v2/blob/master/aws/external/config.go#L32-L37

**Comment by nsf** [comment]
Hm, sorry for a bit of spam here. There is LoadEnvConfig which loads that generic config. But there's also LoadDefaultAWSConfig, which returns a proper aws.Config type. It seems to be working:
![aaa](https://user-images.githubusercontent.com/12567/37538837-b6e75602-2973-11e8-85d4-1892564a0b79.png)

**Comment by dtenenba** [comment]
I can't reproduce that, I get no completions.

There's still a problem with other objects. I've added some code to the example, please do a git pull.

The `result` object should definitely have completions, its documentation is here:

https://godoc.org/github.com/aws/aws-sdk-go-v2/service/s3#ListObjectsV2Output

**Comment by nsf** [comment]
It works: 
![aaa](https://user-images.githubusercontent.com/12567/37539144-c0cc4672-2974-11e8-9afa-ecd2076e67a9.png)

But you need to make sure all packages are installed. E.g. `go get` each package.

Gocode doesn't care about source code right now. It uses only compiled packages.

Also you can run gocode in debug mode it will show some info about resolved/unresolved packages, run in a separate terminal instance: `gocode close && gocode -s -debug`.

**Comment by dtenenba** [comment]
It works now after installing each package manually with `go get`. 

In my real project I am using `dep` to manage dependencies and apparently it did not compile packages, just download source?

Anyway, thanks and sorry to waste your time.
