### ISSUE TITLE
panic: rpc: can't find service RPC.RPC

### ISSUE THREAD

**Issue by fa93hws** [nsf/gocode#520]
I got error
```panic: rpc: can't find service RPC.RPC```
when I type command
`gocode status`, `gocode set` or `gocode close`

Console shows that the error is in 
rpc.go:86

**Comment by fa93hws** [comment]
Ok I restarted my computer and everything works fine now

**Comment by antaln** [comment]
Happened to me after upgrade via vim-go's `:GoUpdateBinaries`, while gocode was still running. `gocode close` also failed with same error. I'm guessing it was an backward-incompatible change in rpc. Killing the gocode process via `kill <pid>` resolved the issue - once vim started new gocode process, rpc worked fine.
