### ISSUE TITLE
company-go can not complete golang third party package ?

### ISSUE THREAD

**Issue by zhangjie2012** [nsf/gocode#525]
like `fmt`, `string`  work well, but `glog`, `mux` ... can not complete.

**Comment by nsf** [comment]
Gocode is no longer maintained, please consider switching to https://github.com/mdempsky/gocode.

It could complete third party packages, however, due to recent changes in Go packages architecture it no longer works for recent Go versions (1.10 maybe and 1.11+ for sure).

**Comment by zhangjie2012** [comment]
OK, I got it.
