### ISSUE TITLE
Does not support relative package paths

### ISSUE THREAD

**Issue by TJSomething** [nsf/gocode#86]
Autocomplete should work for files that are referenced using a relative path.

For example, say that I have a directory tree:
./pkg/pkg.go:

``` go
package pkg

func Random() int {
    return 4 // Determined to be random by die
}
```

./app/main.go

``` go
package main

import (
    "fmt"
    "../pkg"
)

func main() {
    fmt.Printf("Your random number is %d.", pkg.<cursor>)
}
```

If I try to autocomplete at <cursor>, I expect an option to finish with "Random()". However, no options are shown. This is perfectly valid Go, so it should work.

**Comment by sarim** [comment]
@nsf I think this should be noted in readme. I made this handy bash func for quickly build `.a` files for local pkgs which are imported locally.

```bash
compile-go-local-pkg ()
{
    find . -type d -depth 1 -exec go build -o {}.a {} \;
}
```
